// YouTube playlists from @MeetingGod_ — each entry links YouTube videoIds to a named series.
// Drive sermons are matched via detected title patterns (see app/page.js seriesKey()).
export const PLAYLISTS = [
  {
    id: 'holy-ghost-encounter',
    title: 'Holy Ghost Encounter',
    youtubePlaylistId: 'PL3vnPo6kbgzX6uIPgbAelotzAGe9mxV-Z',
    videoIds: ['hl4NXSiLFio','BT88rRaZ_dE','UqoduxaIcSk','uJhfjMv2fNU','d7UaN0cOgiQ','7tg4kpOci1o','7vboHLP_A4Q','JMXSpK9ez_M','_jdXiNBge7g','IzXdXXuHACg','8WKqMkTdUiE','xs7r0BdIvok','SQF3uyprmQ0','4DYspwS_-lY','tWMDX7dSbPI','yjaJWg3rsTA','Tsl-gUxlzR0','bOQFBeuXjm8','KUFOYKlblvM','pEk2KZtjx7o','GB0WIb4wjhQ','awfnGUok6WY','60oZhw6Junw','7Iv1QkoYNMQ','GqMX2RKNsQU','p1cH_SoKU4k','aWxLgRartCs','YSVm2LvYHZk'],
  },
  {
    id: 'meeting-god-series',
    title: 'Meeting God Series',
    youtubePlaylistId: 'PL3vnPo6kbgzX06aJzPKkc6sNRR1YOeReR',
    videoIds: ['N6yh62_otOs','HuOIRD7ocIw','i_NxEsVGKd0','F3IFXXenNto','DKM-j7rpwg4','DpXMs9wa-10','jJcYILHaHbk','ZbJV1wP-h74','E597t0NQwkI'],
  },
  {
    id: 'the-holy-spirit-series',
    title: 'The Holy Spirit Series',
    youtubePlaylistId: 'PL3vnPo6kbgzXXqA9Zeb5r6sM8ijABWaTB',
    videoIds: ['VyzvoQHUSpI','d6ItkJWpaxQ','s99_dVGKyvU','kyluXCkiDTE','gIO_xoZ5-bI','I--Gz6zPzow','ddTWzhy1uys','CmvGVYOqLnc','sfOxNH9eU7w','7KRLIAcbNaw','zwTKr_SxpfA','xHl7yyYgLU0','ilBFn1sL4mQ','jnHzKYpjaDw','EoQKZsUw9EA','DZdE6wFK79o','MK9hhCqL9Hc','QjSp7Y5vxCI','hNQ-tjXiD1g'],
  },
  {
    id: 'sweet-influences-holy-spirit',
    title: 'Sweet Influences of the Holy Spirit',
    youtubePlaylistId: 'PL3vnPo6kbgzWEsksecFcY8ad59f_KkAt1',
    videoIds: ['UAsrqlA7tMQ','BQce7G-EZyc','KNi1bsFpcqY','RkxBnoHjzIw','NbGvEfeZF0U','-RZSfesDRcQ','gLnsRMvuxa0','xwoWyGTyCmI','S53hwiV6B_w','cV0LQfebors','g7FNE9EGSsg'],
  },
  {
    id: 'presence-of-god',
    title: 'Presence of God & the Supernatural',
    youtubePlaylistId: 'PL3vnPo6kbgzVdVgOPvdbjrLZ9GbhBAwLV',
    videoIds: ['4Z_AU_Iqw3Q','vvJsIpwp7dM','KWoaiY1loco','UBStolOOL2U','bP7lYhbso-Q','d0T0h6BYs4Q','RRJycni98Ug','r36QZxl4sM4','bg4IBXgG3A4','hf_uglIhxt4','l8Hjhhl7KAY'],
  },
  {
    id: 'prayer-series',
    title: 'Prayer Series',
    youtubePlaylistId: 'PL3vnPo6kbgzWa-WuEQLCWQT42v7axOTE4',
    videoIds: ['4DYspwS_-lY','yjaJWg3rsTA','Tsl-gUxlzR0','bOQFBeuXjm8','KUFOYKlblvM','5wwv2lgV2dg','CZeBZuuSDaY','y3wZmnZywac','5XMmka1ajZ8'],
  },
  {
    id: 'prayer',
    title: 'Prayer',
    youtubePlaylistId: 'PL3vnPo6kbgzV4tTca5w7u9XD3pb8nJjFe',
    videoIds: ['2DTvHilUz6g','58Khj3668XA','94rOtjl7rrc','SjN_1ebXaCs','UErFSur--tg','ZdNIMLLhNUE','ea3JuPUq61I','mNSY0o6cs1Y'],
  },
  {
    id: 'shepherding-series',
    title: 'Shepherding Series',
    youtubePlaylistId: 'PL3vnPo6kbgzVsZGOsXaxoSRBRaV-apqRO',
    videoIds: ['XdIq-EJ05-c','_67jZKeT4OM','dT1FZ1AyNPk','kvBJGD6mlUI','mcTobRTaeRY','nm-8XY-ig7U','o84m5Y6we7w','sVwZidbsPO8','uaa4-pYYVXc','0t06iDZCS-s','7hW0Yx8G4Yk','9XYmiigwReE','CQvV1W2a5rA','Jq_M1Jz6jKI','KNlN6TEZJsE','KYApS8CnlOI','XkwoUyIbYbA','aXrVEfKaEb0','c24-CBCGH3I','lURiaUtOI0k','psgvtOLwPPI','vKjJVuqCly4'],
  },
  {
    id: 'spiritual-growth',
    title: 'Spiritual Growth',
    youtubePlaylistId: 'PL3vnPo6kbgzWEuf5yPsrOtOQJU43SRmCr',
    videoIds: ['EoOkm38dsjE','5ONSsXlxex0','XghII-nOQrw','yu8IlfRoxR4','74-FfDYGsrU','EFse4SQQ24s','LHZQGJDljWw','M-pqT5fIhEg','2jTJftgsN7Y','Q6_Af9qx-xw','vMcgOPlkzDk','RaLlzfpSwL8','UdP__aTKvXQ','d0fE35y3sVw','eOzg427hSkM','mu2s1nHSsQM','xuVepo-hEXA','pir4c0SFTaQ','oQwRNrzMfac','55raMOGR5L4','e_QZAI1ruS4'],
  },
  {
    id: 'salvation-series',
    title: 'Salvation Series',
    youtubePlaylistId: 'PL3vnPo6kbgzXh13d84EdcT1rvi7VYE0ly',
    videoIds: ['0x3LiOC5lm0','90l0U1zgZdw','9el1SQrdFmM','J_lQARe4P8Q','PlHOHg4uIPg','VvTY-dX7t0E','f_SSeowDc-w','gb0t0zomg5w','gjY6UcPwTQg','i6EmjEz8kOw','if-iGhdBvIg','o-61QpA3_pE','wtAY4yfU1Go','y-Pp4wfdBZk'],
  },
  {
    id: 'anointed-and-his-anointing',
    title: 'The Anointed and His Anointing',
    youtubePlaylistId: 'PL3vnPo6kbgzVBowo2azpJg2gyhqrw6r82',
    videoIds: ['ADH05ejjLTQ','ISLJxAqwAPw','9CfpkXE-3Fs','hgmwYcs52O0','o7L2HysmI58','lcOmEBXw6rw','eW5ahuc7QaA','1YnYo2OYr9o','vtrafi7f96o','1kYFh13-sIs','IZQriFwoibo','1qrYvY18PEU'],
  },
  {
    id: 'god-has-friends',
    title: 'God Has Friends Series',
    youtubePlaylistId: 'PL3vnPo6kbgzXDelotFAzMLfA720IOAPw4',
    videoIds: ['2ebOBrveMgc','qjmpxDQN1Cg','t3eaNOMx44A','OqJ-BrLZVeI','wsIuuqgPU8w','wDOGB5xqLf4','KgVTRipVI94','C146E1ltAm8'],
  },
  {
    id: 'pleasing-god',
    title: 'Pleasing God Series',
    youtubePlaylistId: 'PL3vnPo6kbgzXbp7olAawnPAt25RBJXVC_',
    videoIds: ['gnGQUpwt0Tk','tlZVYy0mn60','6i_dEnj40pk','YfSkdCIE2U4','1q8pw9_QO5o','8EPWoAbcN1M'],
  },
  {
    id: 'stir-it-up',
    title: 'Stir It Up Series',
    youtubePlaylistId: 'PL3vnPo6kbgzVgaxsQlwNGpZDLYJnjboZD',
    videoIds: ['W3H7bTNuRAk','ss-wO1i0IhE','wOZ_DvREHks'],
  },
  {
    id: 'foundations-of-ministry',
    title: 'Foundations of Ministry',
    youtubePlaylistId: 'PL3vnPo6kbgzVE_dBRhMWERpDCRNr01djI',
    videoIds: ['6qJX_KUeYKI','kh6-YoIBnGc','YxOoANE-0r0'],
  },
  {
    id: 'phanerosis',
    title: 'Phanerosis',
    youtubePlaylistId: 'PL3vnPo6kbgzVX2WzUd2Qt8zNlKqWsN8M2',
    videoIds: ['JHCqxHunCDM','V422cqs37Tg'],
  },
  {
    id: 'quiet-time-series',
    title: 'Quiet Time Series',
    youtubePlaylistId: 'PL3vnPo6kbgzVqCXzXzpa8hZ-NZ9AyJTCR',
    videoIds: ['yHl1AdKvdGs','Y6fFq9Hq-6A','0ZBpvl4O_No','FozYiEA60jE','ozvAJMQ5Nek'],
  },
  {
    id: 'names-of-god',
    title: 'The Names of God',
    youtubePlaylistId: 'PL3vnPo6kbgzWftKBjal4ik6CLLWdFvvpI',
    videoIds: ['glYte8jqDoY','waH0CJjLHGg','TE-D2y1OIUY'],
  },
  {
    id: 'transform-pastoral-ministry',
    title: 'Transform Your Pastoral Ministry',
    youtubePlaylistId: 'PL3vnPo6kbgzXFUVHFVZpqXQTFqIk9tAvr',
    videoIds: ['lCTn_Vtk3HA','ONxom_tQZGY','UyH25mODOyg','Eko4ka6adOM','wAFnILSlMio','3q651LWnI4M','BX84F-_8AiU','fWKeKjcmIxM','tx4kY9KUdsA','SmXu3e855O8','swBZYnynvqw','3C-17J_6TvQ','3coes81RF2Q','VXFxwzySIaw','k-1lrMVM86A','TAopyZ-NcsQ','I0O5hCudZtY','1tNsiH6A7zQ','N4S-rk6eCs0','6_zvNOj62RU','q4oeMxHMgtw','z2NaxjnkJrE','gBgoMu8yBcQ','fUO9dos8nKw','m6tyqMUw3H8'],
  },
  {
    id: 'classic-messages',
    title: 'Classic Messages',
    youtubePlaylistId: 'PL3vnPo6kbgzWM2hrGqH5hx4l_2ov5vEVs',
    videoIds: ['eriMY5ZHx9A','KUFcUIXWO9o','Pp1v0JN5qfc','32yKeo4vbJE','5E4RQVeykiE','Al69U15zbe8','x_27D9ZNKg4','8EAZ8LTLS3s','8_fU9uUzOx4','DgW1UAmXmWQ','Ks0LkSqgLBc','uaB_2PFVkdw','Wt7fh1FJM_k','XOP5NJzrThk','Yifgbqgm09s','agipC9XhVC8','caSy1ft6u24','hqZ89h88cQg','qJP6res5n4c','qTas2ie1TMY','LvDcywoCkMg','sMVBnBaiskI','Oko_WnuHCws','n3jRbJ0W0jI','0UxRlq1ZcEI'],
  },
  {
    id: 'leaders-services',
    title: 'Leaders Services',
    youtubePlaylistId: 'PL3vnPo6kbgzXgxWEV0f01YMnvbbJuGvrj',
    videoIds: ['GcamB9A2hQQ','JL0Tn8IaX1Q','MzVSmD2klbM','NzaRqof29VU','O1YVgm6kR_o','oo4Vbzm0f7o','yzjeIhSWXHw','cUuOUKw46NI','RQjB6zSMXZ8','MzkX48DEyBA','g3PCE93HQr8','HgMZINOIL24','GtdlLwS77vE'],
  },
  {
    id: 'poison',
    title: 'Poison',
    youtubePlaylistId: 'PL3vnPo6kbgzUY_J9oGPFU94xpS1xyIdu2',
    videoIds: ['XTTgWnEINp4','Lubqkuxe6Yc','Luwtqm7BxJY','Snx2S5Hsq8Q','wnFC0I7wImg'],
  },
  {
    id: 'backsliding',
    title: 'Backsliding',
    youtubePlaylistId: 'PL3vnPo6kbgzWcyJcVC4Q1xZhiwsWbpdK5',
    videoIds: ['FnAkGA39Vl4','ZO-OVUQejg0'],
  },
  {
    id: 'jesus-series',
    title: 'Jesus',
    youtubePlaylistId: 'PL3vnPo6kbgzXino9hEcPmXlMWmxOuhEa8',
    videoIds: ['0_YSAS_PdGc','514AOEJm0t8','Cx_LFu85Hco','NRAElRNyd-A','WFeqnnqiTXw','cYHVdlnY130','d3he1eNep_I','yJ0efi4leqs','pfIVKYO-QIM','BBOqToFkmP0','s3uuEEhl4lA'],
  },
  {
    id: 'tuesday-meeting-god',
    title: 'Tuesday Meeting God Service',
    youtubePlaylistId: 'PL3vnPo6kbgzXDxKVrJHkrFAzOotQdkqlA',
    videoIds: ['TE-D2y1OIUY','gnGQUpwt0Tk','hnKbMu_FT60','tlZVYy0mn60','6i_dEnj40pk','YfSkdCIE2U4','8EPWoAbcN1M'],
  },
];
