export const SERMONS = [
  { id: 1, title: '#Two Guys - Art Of Hearing - May 6th 2020', keyScripture: '', summary: '', driveId: '1Q2ZtQD7ssJQmL-DW5HSAwwS6pI-0oscB' },
  { id: 2, title: '01 Becoming A Soul Winner', keyScripture: '', summary: '', driveId: '1cMOAYRLpD4KJGDhtic938HKc7SGsbmQ6' },
  { id: 3, title: '01 Burning Vision', keyScripture: '', summary: '', driveId: '1-pOte7NUlb0ZK0f2JJ75Fq_1OMLqNSBM' },
  { id: 4, title: '01 Indwelling of the Spirit', keyScripture: '', summary: '', driveId: '1OHbgB_Oj2Dz-C0-fR2sQhB744wr3nVTP' },
  { id: 5, title: '01 Knowing God', keyScripture: '', summary: '', driveId: '1KEU_ClSOcuXvjRDjeU6CaFG-HaxTM3oE' },
  { id: 6, title: '01 What it means to be Humble like Jesus', keyScripture: '', summary: '', driveId: '1itQf0Ft4U8PSAC-ph-4OAoo4JepyQfUy' },
  { id: 7, title: '01.13 - Victory Secrets - The secret', keyScripture: '', summary: '', driveId: '1QI9mvs-iX8r_sSqoRQBcxTzHBDFJe60S' },
  { id: 8, title: '01.20 - Praying in the Spirit', keyScripture: '', summary: '', driveId: '1tB5oApPpqOagVuEv2-ZoWO8pPZ9Y_l9u' },
  { id: 9, title: '01.20 - Why You must pray', keyScripture: '', summary: '', driveId: '1haWNU8SXOHvoqCLBjzEputeJHkZTCkwK' },
  { id: 10, title: '02 Becoming A Soul Winner Part 2', keyScripture: '', summary: '', driveId: '15gCHFmw1IjADSOuLolF1edgEutSwcRYB' },
  { id: 11, title: '02 Knowing Part 2', keyScripture: '', summary: '', driveId: '1cCicT_PNCITwrxpaHuO9Q7qTy6HDUzYF' },
  { id: 12, title: '02 Phanerosis 1', keyScripture: '', summary: '', driveId: '1zxDZp0LIwezcvKFSKTeYfX5onw5eyYgT' },
  { id: 13, title: '02 Shepherding Techniques That Lead to Church Growth', keyScripture: '', summary: '', driveId: '1P0Jqut_WdXJR2I9Q3hUJ449qupCCtxAH' },
  { id: 14, title: '02 The Presence of the Holy Spirit', keyScripture: '', summary: '', driveId: '1pwANG3O1-WVtSvHf4iyA0qh6jKZItWhs' },
  { id: 15, title: '02.06 - 100_ Answered Prayers', keyScripture: '', summary: '', driveId: '1PwYQ1ZEv5mAD-p7ppY9ITjGxd629cVju' },
  { id: 16, title: '02.10 - Legon - Quiet Time', keyScripture: '', summary: '', driveId: '1l3lFS2donG0_5LnK2nrxJpo6kDBBlNAI' },
  { id: 17, title: '02.10 - Quiet Time - Legon', keyScripture: '', summary: '', driveId: '11bQulAjx8pgiYy798CQbki1Ytu6ktVia' },
  { id: 18, title: '02.10 - Why This Teaching About Curse', keyScripture: '', summary: '', driveId: '1ExNjxZXEw-g3WO9Ye-fuaDZW4sfJ4giY' },
  { id: 19, title: '02.12 - Flow with the Holy Spirit as', keyScripture: '', summary: '', driveId: '1MX0wodIXau08XsXXrFXH3rJG0HtlgI1D' },
  { id: 20, title: '02.17 - The Global Curses - Neutralis', keyScripture: '', summary: '', driveId: '1rZP34354qWwkJM96rQWIQkRpQHdw4F-G' },
  { id: 21, title: '02.19 - The River of the Spirit', keyScripture: '', summary: '', driveId: '1Cv4MkWPZifoxb7jIbx93aQ4R-latKxUm' },
  { id: 22, title: '02.24 - ABMTC - Jesus, a Man of Anoin', keyScripture: '', summary: '', driveId: '18RdK7aVVVygPUSoAh9qrkMJWcHiZr3D9' },
  { id: 23, title: '02.24 - Jesus, A Man of Anointing and Miracles - ABMTC', keyScripture: '', summary: '', driveId: '1hU5NcPQ4_MTJFBxeBJeXzVgJ9vUrnj3N' },
  { id: 24, title: '02.24 - Neutralising The Curse - Top', keyScripture: '', summary: '', driveId: '1IJss4nX_MTt5Jvr4YUctF2bwld8YIune' },
  { id: 25, title: '02.24 - The Curse of Eve- Neutralisin', keyScripture: '', summary: '', driveId: '1PdLcYtErMdJaCcrjBYQn0m7DsDiLbBKA' },
  { id: 26, title: '02.25 - ATU - Jesus, the First and th', keyScripture: '', summary: '', driveId: '1Hkdg7_LYUFEFkKYEY9jPs6s2z7KGvooq' },
  { id: 27, title: '02.25 - Jesus, The First and The Last - ATU', keyScripture: '', summary: '', driveId: '1bQwyIFN7xQCJ533zEenhwsBOx2jGedSk' },
  { id: 28, title: '02.26 - The Holy Spirit and Soul Winning', keyScripture: '', summary: '', driveId: '1oq8DX7MKEjWWe0tNQ0jzrgqV1iZvM8C9' },
  { id: 29, title: '02.26 - The Wind of the Spirit', keyScripture: '', summary: '', driveId: '1FC50HaG-RFS98NfipcsCs2vXOOtQmVf2' },
  { id: 30, title: '02.26 - Why Phillip Preached Christ', keyScripture: '', summary: '', driveId: '1jO-7mxaQT5qFJGDB5YYF_iLZHS8xFd33' },
  { id: 31, title: '03 Becoming A Soul Winner Part 3', keyScripture: '', summary: '', driveId: '1eOzF77M7F3QF4tfF6jFeD6vxZEpnXukZ' },
  { id: 32, title: '03 Holy Spirit-Led Minister of God', keyScripture: '', summary: '', driveId: '1sVRXbs743MhNRpiZQKS_1ZzYRxEAnkxE' },
  { id: 33, title: '03 Knowing God Part 3', keyScripture: '', summary: '', driveId: '1g6IepH9zysaHEXpIo2KmSiUALNek-k1j' },
  { id: 34, title: '03 Shepherding Techniques That Lead to Church Growth Part 2', keyScripture: '', summary: '', driveId: '1bOkqEbZlRIETuv3jtTzQrOCGSFNZN9DB' },
  { id: 35, title: '03.02.2024 One Thing Is Needful 2', keyScripture: '', summary: '', driveId: '1S4rpcYMCQAkaB9C6l9YlRTckxlKBmChZ' },
  { id: 36, title: '03.02.2024 The Sweet Influences of the Holy Spirit on your character 4', keyScripture: '', summary: '', driveId: '1JEzfIfA_nh3ZSuW65QG8lidZBjhbmb4C' },
  { id: 37, title: '03.03 - Neutralising The Curse Pt. 2', keyScripture: '', summary: '', driveId: '1bfSK-WT2ocTo_uZdLF93F4-R4DyTltlY' },
  { id: 38, title: '03.03 - The Church and Barrenness - C', keyScripture: '', summary: '', driveId: '1cChwDF5SG-DP5CC9ojxdCnEO2MGlpJvR' },
  { id: 39, title: '03.05 - Flowing With The Holy Spirit', keyScripture: '', summary: '', driveId: '1vv9L4WWxLsXLSJHvutQfVZlZ8O_uXXJU' },
  { id: 40, title: '03.05 - Flowing with The Holy Spirit as A Dove - Gospel Encounter', keyScripture: '', summary: '', driveId: '1KwQsgr5pOTNsgIs1R-UDL5Aua1aT_r9V' },
  { id: 41, title: '03.10 - The Church and Barrenness - C', keyScripture: '', summary: '', driveId: '18HNERqmjC4J9TphO0MsbRQpuNpg_SRHw' },
  { id: 42, title: '03.12 - The Presence Of God - Why You', keyScripture: '', summary: '', driveId: '1yK2F8w1oGS5Jnv-01xJq9UOrLdhmBJuk' },
  { id: 43, title: '03.13 - Why People Don_t Pray Everyda', keyScripture: '', summary: '', driveId: '1SdhE9wabwxt8m730AcIhzeqiX9u-VRND' },
  { id: 44, title: '03.15 - City Church - Steps To The An', keyScripture: '', summary: '', driveId: '1d09lls6CAGgqoRy4gWxYCP18-Y1AQo7b' },
  { id: 45, title: '03.19 - What every Christian should k', keyScripture: '', summary: '', driveId: '12WN9xhdBI3LQoD517UkWrPMknAfjiOra' },
  { id: 46, title: '03.20 - How to Watch and Pray', keyScripture: '', summary: '', driveId: '1zbHNcWmGFbR7sbuFCjs8LmirOSCLokoy' },
  { id: 47, title: '03.24 - The Church and Barrenness - C', keyScripture: '', summary: '', driveId: '1VZNFPLxDdMAXY1VxW3nrHZjtY8O978f-' },
  { id: 48, title: '03.26 - The Laws of the Supernatural', keyScripture: '', summary: '', driveId: '1YEmE9rVXvudch-3MtbYkD1FDVvvsMmVP' },
  { id: 49, title: '03.27 - The Key of Watching and Prayi', keyScripture: '', summary: '', driveId: '15hZumQ7J80NGIsmDQh0NCQ2uS-F33p2M' },
  { id: 50, title: '03.31 - 15 Essential Features of a Sh', keyScripture: '', summary: '', driveId: '1DKiHhH3GvLsjTltuHnF9fr5erf2S0Qzz' },
  { id: 51, title: '04 How to Become a Fruitful Christian', keyScripture: '', summary: '', driveId: '16a9fs3YYtzOm7tQLjcXnGucS916S-XQt' },
  { id: 52, title: '04 Man is a Spirit, has a Soul and lives in a Body', keyScripture: '', summary: '', driveId: '1YKy3ZI3NTUvd4ef51dhu_lbeNiXCHoUG' },
  { id: 53, title: '04.02 - Losing', keyScripture: '', summary: '', driveId: '1eVIiigctCbrfp1NGcxkPt6QP5URcGcrb' },
  { id: 54, title: '04.03 - The Qualities Needed for Watc', keyScripture: '', summary: '', driveId: '1TZkARdcFjJnIPw9Bv9T97QW1uLEFDiRr' },
  { id: 55, title: '04.07 - 15 Essential Features of a Sh', keyScripture: '', summary: '', driveId: '1U3K84YqMwlcXvGg8fBUEuT2W2ecLbZeH' },
  { id: 56, title: '04.08 - The Sweet Influences of The Holy Spirit on Your Knowledge of God Pt. 1 - Holy Ghost Reminders', keyScripture: '', summary: '', driveId: '1R41qXSAu73xRNCDNud4TDA9gAdYWUHUB' },
  { id: 57, title: '04.09 - Why You Need The Presence of God Pt. 1', keyScripture: '', summary: '', driveId: '1dbQrVrqR638LI2kI1CKoX-4qGwBUJZxJ' },
  { id: 58, title: '04.14 - 15 Essential Features of a Sh', keyScripture: '', summary: '', driveId: '1Zkkp6tRFlP41idolCt2DcVaTDKp66VOs' },
  { id: 59, title: '04.15 - The Sweet Influences of The Holy Spirit on Your Knowledge of God Pt. 2 - Holy Spirit Direct Teachings & Guidance Into Truth', keyScripture: '', summary: '', driveId: '1Eyb8DWQlRH3zX18DVPemkGvDVxtbdF-r' },
  { id: 60, title: '04.22 - The Sweet Influences of The Holy Spirit on Your Knowledge of God  Pt. 3 - Holy Ghost Knowings', keyScripture: '', summary: '', driveId: '1sXIIKwEbEwJc0MWxW3IE_GrkQhJ_dOZX' },
  { id: 61, title: '04.23 - Take My Yoke and Learn of Me', keyScripture: '', summary: '', driveId: '18Rlc4suR4_WT3R_X3PvzbhWrc5LSMe8u' },
  { id: 62, title: '04.28 - The New Creation', keyScripture: '', summary: '', driveId: '1NH3wPzmwklxQq39uL1X6S5-Hr3eIU6DP' },
  { id: 63, title: '04.30 - Why You Need The Presence of God Pt. 2', keyScripture: '', summary: '', driveId: '1f3bDZ3GSb_F_CZmViKJUmumyvzDfSInD' },
  { id: 64, title: '05 How to Become a Fruitful Christian Part 2', keyScripture: '', summary: '', driveId: '1b49LAl3j_sOK6nVo_oVso8hL6utq2WTn' },
  { id: 65, title: '05 The Spirit of an Unsaved Man is Dead and Desperately Wicked ', keyScripture: '', summary: '', driveId: '1gBcg3Wlvx03TMNwLJtBllNDy5OzWcoL3' },
  { id: 66, title: '05.05 - The New Creation Pt.2', keyScripture: '', summary: '', driveId: '1b0A7Yc9NaBDuiuzjxPXtChM9lMyRpTzL' },
  { id: 67, title: '05.06 - The Sweet Influences of The Holy Spirit on Your Knowledge of God Pt. 4 - Spirit Led Men of God', keyScripture: '', summary: '', driveId: '13YBfo0kCkHa2pAsCh6aa93gye7UzyGOA' },
  { id: 68, title: '05.07 - Why You Need The Presence of God Pt. 3', keyScripture: '', summary: '', driveId: '1OIzlr9ohjp5S3jITzPApCYfvIXDthz2b' },
  { id: 69, title: '05.12 - The New Creation Pt.3', keyScripture: '', summary: '', driveId: '1iSn8A5IVKUCs3d3Q8dHjWNHFlwlG6h1G' },
  { id: 70, title: '05.14 - 7 Lessons Learnt From The Life of Our Founder', keyScripture: '', summary: '', driveId: '1OnoVf7exSRx2UagGPDXmkWCSEmgQTSCH' },
  { id: 71, title: '05.14 - UPSA - Accessing the Holy Spi', keyScripture: '', summary: '', driveId: '1PlF_czL7KIL9KMl-hhScQQIzcb1uNoHK' },
  { id: 72, title: '05.19 - The New Creation Pt.4', keyScripture: '', summary: '', driveId: '1GrwRO2kb-2NSV2dnSVA_LYQ3RDXjUr9h' },
  { id: 73, title: '05.19 - The Three Rewards of Honourin', keyScripture: '', summary: '', driveId: '1adO3-klQizS0rxbseg_ixkSxdZpFqI1U' },
  { id: 74, title: '05.21 - Honour', keyScripture: '', summary: '', driveId: '1CqzT0vE5W62Ru_wYSg8L8ZZ0S6fZQnKO' },
  { id: 75, title: '05.26 - The New Creation Pt.5', keyScripture: '', summary: '', driveId: '1ee1LMJFIuXKOP0PV_egJS4NESzMF4ZrI' },
  { id: 76, title: '05.28 - Foundations of Christianity', keyScripture: '', summary: '', driveId: '1FHsbmoqZKuVJdGp0Cs9wxwrbaNGhwBST' },
  { id: 77, title: '05.28 - If You Love The Lord, Expect These Blessings Pt. 1', keyScripture: '', summary: '', driveId: '1MD9VjyhzTgTdRSXJKu2GcA6RD4iNJb2g' },
  { id: 78, title: '05.29 - Korle Bu - The Holy Spirit', keyScripture: '', summary: '', driveId: '1Y6i85cLE4Tyc0PkHr5evlHYiSIV0uJ5p' },
  { id: 79, title: '05.31 - Legon - The Holy Spirit', keyScripture: '', summary: '', driveId: '1rRmoU5n2BZmNW4nnIirOrJKO703FUlMJ' },
  { id: 80, title: '06 Stir it Up_ Obedience', keyScripture: '', summary: '', driveId: '1EvAClvkwt-j_YdCP1H9g_2bqV6LlnsBb' },
  { id: 81, title: '06.01 - The Presence Of The Holy Spir', keyScripture: '', summary: '', driveId: '1As_qhuzq0KuBYLSc4-ek41w3b5TcHJ2u' },
  { id: 82, title: '06.01 - The Presence of The Holy Spirit Pt. 1 - City Church', keyScripture: '', summary: '', driveId: '1_uYIGTRUkfRF0bg3tBJ2HDpasgtXAo1E' },
  { id: 83, title: '06.02 - The New Creation Pt. 6', keyScripture: '', summary: '', driveId: '1NjNWdFfF64u1bOHo-TtY3Gmxm5mCZKE4' },
  { id: 84, title: '06.02 - Why Non-Tithing Christians ar', keyScripture: '', summary: '', driveId: '1SSp-9yNqGvh05D8HAdKBC1WBs6pK_fMv' },
  { id: 85, title: '06.04.2020_ZoomFLNorthAmerica_Holy Spirit (Q&A) ', keyScripture: '', summary: '', driveId: '165oWefR2dKNMFwIh9yPTCQo8uVyb9HrT' },
  { id: 86, title: '06.08 - The Presence Of The Holy Spir', keyScripture: '', summary: '', driveId: '1rtICn1XMtoBF14gzaCkZVVOSXC6UlEhV' },
  { id: 87, title: '06.09 - Why Non-Tithing Christians ar', keyScripture: '', summary: '', driveId: '1S2EdtLkrCXX9za2GJcMAtm2We53DeaTO' },
  { id: 88, title: '06.10 - The Voice of the Holy Spirit', keyScripture: '', summary: '', driveId: '1hnouL1_G91r8_rkptztt9SKcWMA_rj4X' },
  { id: 89, title: '06.10 - The Voice of the Holy Spirit - City Church', keyScripture: '', summary: '', driveId: '114_LE7O2tyQFt3W4w3TslSnnVHk4sMyJ' },
  { id: 90, title: '06.11 - If You Love The Lord, Expect These Blessings Pt. 2', keyScripture: '', summary: '', driveId: '1Q1td-09v894DB60JL3XeX8zXjAOjudc2' },
  { id: 91, title: '06.12 - ABMTC - The Holy Spirit', keyScripture: '', summary: '', driveId: '1XHkpOcasVqjNHuJgpWtgROxOYhZr-o1g' },
  { id: 92, title: '06.18 - Wisconsin- 7 Steps to the Ano', keyScripture: '', summary: '', driveId: '1Z8k4Kvljmj918pWVSGnv-5hRCzPlSZ5V' },
  { id: 93, title: '06.20 - Dansoma - Understanding The H', keyScripture: '', summary: '', driveId: '135FHw7Tnii4-os0yahy01NxQZPbtHVFY' },
  { id: 94, title: '06.21 - Reason Why People Dont Use th', keyScripture: '', summary: '', driveId: '1vRUL6H2jdk8nOlfkt0kCr8g-AsH3sQ50' },
  { id: 95, title: '06.22 - Be Led by the Spirit of God - Leaders Service', keyScripture: '', summary: '', driveId: '1y4Bcsh0_2-ZsTeJc6pLD5aFOl1d3-MOQ' },
  { id: 96, title: '06.23 - The Art of Following David', keyScripture: '', summary: '', driveId: '1n9v8AnAu9FVHynZRbG_VuHzHqQDKnbx1' },
  { id: 97, title: '06.24 - The Voice of the Word - Leaders Service', keyScripture: '', summary: '', driveId: '1cYnI_yVphfqNB9ASe2_xmLoDvJqZz2Gj' },
  { id: 98, title: '06.30 - ABMTC - The Sweet Influence o', keyScripture: '', summary: '', driveId: '1vU13hmfih6N-fobsWZCmTcJ6TjOXhSqA' },
  { id: 99, title: '06.30 - The Art of Following David Pt', keyScripture: '', summary: '', driveId: '1DSOwwCg8nWAuHSIocKlXUzomOcDiIpsK' },
  { id: 100, title: '06.30 - The Sweet Influences of The Holy Spirit on Your Becoming A Pastor - ABMTC', keyScripture: '', summary: '', driveId: '1D3Wo-HbjCRCPhbIIxbqQdQQB79H1f7Iv' },
  { id: 101, title: '07 The Spirit of a Saved man is Righteous and Truly Holy', keyScripture: '', summary: '', driveId: '1al3v3rjRMj2j-HPrnUn9XLaA0RTXO4xZ' },
  { id: 102, title: '07.04 - Kasoa - The Holy Spirit', keyScripture: '', summary: '', driveId: '1T6JesTyZcnL8f1XJpWUnJ40NFg4FThPb' },
  { id: 103, title: '07.07 - Jesus Is Anointed For You - Kwabenya', keyScripture: '', summary: '', driveId: '1oclDr2OtuTGA3CC790XKrzca53TLi_B1' },
  { id: 104, title: '07.07 - Kwabenya - Jesus is Anointed', keyScripture: '', summary: '', driveId: '1Br-5r7gQSYG_l_5msuK3Edx2v7nt4jy2' },
  { id: 105, title: '07.07 - The Art of Following David Pt', keyScripture: '', summary: '', driveId: '1_N171EYT7IHviy_aovelvb-kjTvKvz7F' },
  { id: 106, title: '07.11 - Maritime - Quench Not The Hol', keyScripture: '', summary: '', driveId: '1s9McUhckjx3BtYdVnwXaLftCyuEHJ85S' },
  { id: 107, title: '07.12 - Ho NTC - Where The Fire Goes', keyScripture: '', summary: '', driveId: '1-Tj2HhnYPLaONXyhaTl82t0Fcz9DW2z4' },
  { id: 108, title: '07.13 - By His Stripes - Dansoman', keyScripture: '', summary: '', driveId: '1H5RRHE4eKhCCmKTU6ZiJOVBw4ETiI8QR' },
  { id: 109, title: '07.13 - DC - By His Stripes', keyScripture: '', summary: '', driveId: '1BLQRmFU1KvEq9ymq_ea7IzlMope80IYY' },
  { id: 110, title: '07.14 - 10 Reasons Every Christian Sh', keyScripture: '', summary: '', driveId: '1RKcBbHAPadg4bvdq4DKNEtc6Tq53HaNq' },
  { id: 111, title: '07.14 - Come Unto Me - Korle Bu', keyScripture: '', summary: '', driveId: '1lbAFEZDw4_-iQdZJ30HOoMM9n48sDYvt' },
  { id: 112, title: '07.14 - Korle Bu - Come Unto Me', keyScripture: '', summary: '', driveId: '1-HrSz3cespPYl0bxblmMAYdP68zj7NOu' },
  { id: 113, title: '07.14 - Steps to 100_ Answered Prayer', keyScripture: '', summary: '', driveId: '1xbAMUwti_eauZ1rmLgNakmHpTjXgj0se' },
  { id: 114, title: '07.15 - Osu - The Sweet Influence of', keyScripture: '', summary: '', driveId: '1PHPY4w11oS5jL4QBk3cH8AN5kcmEcuIm' },
  { id: 115, title: '07.21 - How to Pray', keyScripture: '', summary: '', driveId: '1fsOrxCb1SZQzVkW4c3rbptG7j49gd5pk' },
  { id: 116, title: '07.21 - Steps to 100_ Answered Prayer', keyScripture: '', summary: '', driveId: '1Wdt3Rn3onM5o5BPgE6QALyltkL07yJ39' },
  { id: 117, title: '07.21 - The Relationships of Spiritua', keyScripture: '', summary: '', driveId: '1Nxop7d_P6ORXE0awbyKzaGdWRQoKaTak' },
  { id: 118, title: '07.22 - North Kaneshie - Four ways yo', keyScripture: '', summary: '', driveId: '1FXNN3nQfVD8ZyVEhEVVe-WeUwLezVY9e' },
  { id: 119, title: '07.26 - Osu - Seeds and Harvest', keyScripture: '', summary: '', driveId: '1y9TXBJ2KBUcxBSCg-bAXIpJZ2VukercD' },
  { id: 120, title: '07.27 - Legon - What is the Manifesta', keyScripture: '', summary: '', driveId: '1FWuKdYJWOP59PlLpGNYCRIb2lm6XyJK0' },
  { id: 121, title: '07.27 - What Is The Manifestation of The Holy Spirit - Legon', keyScripture: '', summary: '', driveId: '1Hom9mOjq3aXVJslu8vLfQo6jK59f5qZq' },
  { id: 122, title: '07.28 - Madina - The Sweet Influence', keyScripture: '', summary: '', driveId: '1Xnffj5BosUi-MC5I_S7HBGnD5kZYhG2g' },
  { id: 123, title: '07.31 - Not Everyone Who Calls Me Lord Shall Enter the Kingdom - Gospel Encounter', keyScripture: '', summary: '', driveId: '1QX5Qbn3CwPMT1WYR8-QTmpPYy5Q5sBT4' },
  { id: 124, title: '08.01 - How You Can Be a Spiritual Ch', keyScripture: '', summary: '', driveId: '18jVX8Qx_fogk9xPDzFq_tpwBDYP7EKhs' },
  { id: 125, title: '08.01 - How to Recognise the Number O', keyScripture: '', summary: '', driveId: '11yuVntOD8R3jKngBnO_mAiWK3rH4B73j' },
  { id: 126, title: '08.01 - How to Recognise the number One Manifestation of The Holy Spirit - Gathering Service', keyScripture: '', summary: '', driveId: '1yHANmDFYeLJdXTQeQ0dtxxGuKAHdEImL' },
  { id: 127, title: '08.03 - Family Health - How to Multip', keyScripture: '', summary: '', driveId: '1oZ7-XAjPeIuh7WxSQfO_egW4_nXNQk-k' },
  { id: 128, title: '08.04 - Lapaz - The Powerful Effects', keyScripture: '', summary: '', driveId: '17r7YFS7MhoHyinE72rG8AtDiQEt1dDnO' },
  { id: 129, title: '08.08 - How You Can Be a Spiritual Ch', keyScripture: '', summary: '', driveId: '1SJWOn77QVI87x9Zlkj3hQNWXtWxeMF9X' },
  { id: 130, title: '08.08 - How You Can Become A Spiritual Christian Pt. 2 - Rising Stars', keyScripture: '', summary: '', driveId: '1zJHYCvQ_V0b7JvKll5_orF_NO0xnb5o6' },
  { id: 131, title: '08.08 - The Sweet Influence of the Holy Spirit - If I Am Not Spiritual, What Am I_', keyScripture: '', summary: '', driveId: '1PQHO7y4vaytVlxHvs-6UVJOWBVUNJ_ZU' },
  { id: 132, title: '08.09 - GTUC - By His Grace', keyScripture: '', summary: '', driveId: '1yrJRkHp9mXejZ-pbXjWYOMWtPTT-J1YK' },
  { id: 133, title: '08.11 - Kasoa - Sweet Influence of th', keyScripture: '', summary: '', driveId: '1Ca3SsfrkajS6Qm-j5BDfn6Ow7heMDsLE' },
  { id: 134, title: '08.11 - Reasons Why Every Christian S', keyScripture: '', summary: '', driveId: '15nYPFQcjuhjyw2I-xG3tbT7RNoSUWr6W' },
  { id: 135, title: '08.13 - British Accra - Sweet Influen', keyScripture: '', summary: '', driveId: '1l1JSi-Z3NqREdKP1_Pl3wP3nLYgfX3_b' },
  { id: 136, title: '08.13 - OLTBB - The Great Commision A', keyScripture: '', summary: '', driveId: '1pIg9IYnk5SNvQqr8aSrDRa_ROI7pbdXv' },
  { id: 137, title: '08.14 - Jesus and Blind Bartimaeus', keyScripture: '', summary: '', driveId: '1N438xulyOIClaSXARJinP16oNHcI916o' },
  { id: 138, title: '08.14 - Jesus and Blind Bartimaeus - Gospel Encounter', keyScripture: '', summary: '', driveId: '1AcJcwNc8eNt11VEPt_RMv3Jpu4CMRJJp' },
  { id: 139, title: '08.15 - How You Can Be a Spiritual Ch', keyScripture: '', summary: '', driveId: '1KjXxlICodQ0BQifVfj4n05tMmA9dCDxS' },
  { id: 140, title: '08.16 - The Strategies for having a S', keyScripture: '', summary: '', driveId: '15Y3QVONsEQRGRqGq4nyjHbc1OEoX00xv' },
  { id: 141, title: '08.18 - Don_t Be Surprised That You M', keyScripture: '', summary: '', driveId: '1oPyCi8irfPqQdU-E3G6JnIaZpO6M6PiN' },
  { id: 142, title: '08.20 - If you love the Lord, you_ll', keyScripture: '', summary: '', driveId: '1vHKeCbeCdAT7oX0TD9Rksnv8iMu2VjBQ' },
  { id: 143, title: '08.21 - Jesus and the Man Sick of Palsy - Gospel Encounter', keyScripture: '', summary: '', driveId: '1skL7CS0yIwhP645FhGrCNnQK9cjecdxZ' },
  { id: 144, title: '08.21 - Jesus and the man sick of Pal', keyScripture: '', summary: '', driveId: '1UcqO2Wrg12JApw-lBKck-vgaOlr8IF8k' },
  { id: 145, title: '08.22 - FLM - Others and Nabal', keyScripture: '', summary: '', driveId: '1Kn-OfclFFChVvu_J3uKmQwc1KxQOAOCz' },
  { id: 146, title: '08.22 - How You Can Be a Spiritual Ch', keyScripture: '', summary: '', driveId: '12zCDg1Uc-ZQu4cXQ5-YY97FUGbqUg9ow' },
  { id: 147, title: '08.24 - Basonta - Pray to Begin your', keyScripture: '', summary: '', driveId: '1TQmEsTHHUAW9gRNZIZ-ivUN302yo_W9s' },
  { id: 148, title: '08.25 - Many Are Called', keyScripture: '', summary: '', driveId: '1nZbUOAe9ZPIsdT0Oc_Qs7etf5Yy26er4' },
  { id: 149, title: '09 How to Become a Spiritual Christian', keyScripture: '', summary: '', driveId: '1_qwF8IWIqbY7eBpqdLUKSxEr429qZ5fN' },
  { id: 150, title: '09.01 - Bearing Fruits Pt. 2', keyScripture: '', summary: '', driveId: '1O6ysKEI_CkCGmAFJm34otMGDn0QJ0Von' },
  { id: 151, title: '09.03 - If you Love the Lord, you_ll', keyScripture: '', summary: '', driveId: '13guk19tiGxZOgUQ0dwuHpogJ8C87pYbo' },
  { id: 152, title: '09.11 - Proton', keyScripture: '', summary: '', driveId: '1KNQC57UaXx-mYMR4Oydg8iNkNuKRcQ34' },
  { id: 153, title: '09.11 - The Good Samaritan', keyScripture: '', summary: '', driveId: '1y3BvJYUoIlOdM67esU3q1G44DJTXNkyv' },
  { id: 154, title: '09.11 - The Good Samaritan - Gospel Encounter', keyScripture: '', summary: '', driveId: '1UlikvG8X9LbQ3r2KlULbhNvFNUEF-d4y' },
  { id: 155, title: '09.12 - Korle Bu - Transformation', keyScripture: '', summary: '', driveId: '1TdXYHHc31eo3ACugz53mx7QziUI_eK2i' },
  { id: 156, title: '09.16 - The Art of Following Nehemiah', keyScripture: '', summary: '', driveId: '154Wwkh-Wglr3M2Q3UA7YrdceIdqg4Mnb' },
  { id: 157, title: '09.22 - Obstacles to Bearing Fruits', keyScripture: '', summary: '', driveId: '1keCkV_8uBwYt_DsAS-jw3xQ_I1F0j_-e' },
  { id: 158, title: '09.22 - What Jesus Did for Others', keyScripture: '', summary: '', driveId: '1NrNDlVaeEDMu12NggI5ERNC3QvVw-v3Q' },
  { id: 159, title: '09.24 - USA - Q&A with USA GSOs and W', keyScripture: '', summary: '', driveId: '1gIa8DmaagcOQ3FvoMDngQY_S4JWKJjmz' },
  { id: 160, title: '09.25 - The Kingdom of God', keyScripture: '', summary: '', driveId: '1z6Jf3p7C6KrjO0QFusI0bkV-34SJiefl' },
  { id: 161, title: '09.25 - The Kingdom of God - Gospel Encounter', keyScripture: '', summary: '', driveId: '1VA-Ego-SAMT8Ci_Uyy6bhs0h_0r7q_4_' },
  { id: 162, title: '09.25 - The Laws Of Fruitfulness- The Experience', keyScripture: '', summary: '', driveId: '17xYak0B22_VU50gi-0N4ikvSOKob4ged' },
  { id: 163, title: '09.29 - Honour Your Prophet', keyScripture: '', summary: '', driveId: '1_Vwamrdc0S3-PxDnE605HKqrwn3DV_0m' },
  { id: 164, title: '1.', keyScripture: '', summary: '', driveId: '1bOinvXwIelxD1Ui4m2gTOzOBcX9Z5k2U' },
  { id: 165, title: '10 How to Become a Spiritual Christian Part 2', keyScripture: '', summary: '', driveId: '1VI8Ytekqb4XuszjQmTDTVzEEDekhse44' },
  { id: 166, title: '10.', keyScripture: '', summary: '', driveId: '1u0_LJ7X1HgywB0JZnMCWI-7KLucHILWz' },
  { id: 167, title: '10.02 - The Blood of Jesus', keyScripture: '', summary: '', driveId: '1mDUz-H8eCSXEYYpEjSDz-E0rAmL3FHdw' },
  { id: 168, title: '10.02 - The Blood of Jesus - Gospel Encounter', keyScripture: '', summary: '', driveId: '1gEkGngmeFHdu9pr9EAAMPFdUMHWCYR8i' },
  { id: 169, title: '10.09 - Many Are Called', keyScripture: '', summary: '', driveId: '1acxZcu3QLT5LCCERikJ6h_gEcNYpglFe' },
  { id: 170, title: '10.10 - Korle Bu - Jesus And The Rich', keyScripture: '', summary: '', driveId: '12aWKIVpeRwF5LxMJjymi1lqBfFsP7pcn' },
  { id: 171, title: '10.13 - Honour Relationships', keyScripture: '', summary: '', driveId: '1Fjqg18s7lGdkljJRq9n7Q593pBNe1TEf' },
  { id: 172, title: '10.13 - Honour Your Prophet', keyScripture: '', summary: '', driveId: '1AFeR8xiMbGUkor0odKhOUOi6eSriCoUu' },
  { id: 173, title: '10.16 - The Characteristics of A Called Christian - Gospel Encounter', keyScripture: '', summary: '', driveId: '1al-HDFgkpbe6Uvr6JOnbDAir0RR4qOSC' },
  { id: 174, title: '10.16 - The Characteristics of a Call', keyScripture: '', summary: '', driveId: '1oRV8B8DhDQk2UH4n_Uwe4Myevby8FCLI' },
  { id: 175, title: '10.20 - Honour and the Anointing', keyScripture: '', summary: '', driveId: '1zmARBWuZ2ORajra-umqyrFHd06ZOFYxy' },
  { id: 176, title: '10.20 - How Honour Releases Power', keyScripture: '', summary: '', driveId: '1hHxfQpOtf-HkZbhDz6NDBrErcgKh9rkU' },
  { id: 177, title: '10.23 - The Limitation of God_s Calling - Gospel Encounter', keyScripture: '', summary: '', driveId: '1JVT73BQk9mHNuG6rfXq8YOYl22SKDaxu' },
  { id: 178, title: '10.23 - The Limitation of Gods Callin', keyScripture: '', summary: '', driveId: '1z2WAac6YlaYPfaofoRBcjAmeetXRiw2B' },
  { id: 179, title: '10.24 - Tell Them - 120 Reasons Why Y', keyScripture: '', summary: '', driveId: '1jsj6JnctZNumuaUslTrhAkiqtaSAqPqh' },
  { id: 180, title: '10.25 - Oyibi - Jesus And The Man At', keyScripture: '', summary: '', driveId: '1vB4JLfBhSj3zas2XuU5NufVn5hJBPthA' },
  { id: 181, title: '10.27 - Why Christians Do Not Use The', keyScripture: '', summary: '', driveId: '11yaSqWkoMMp4pKUnnin-i2PRpUxWDyGu' },
  { id: 182, title: '10.29 He that has and He that has not', keyScripture: '', summary: '', driveId: '1FufuUlqHO5hdVvENfGzm475Mx5TWfvkH' },
  { id: 183, title: '10.30 - Responding To The Call of God', keyScripture: '', summary: '', driveId: '18bL_td60za2BT-66x6FYGGpk8WCFKGXD' },
  { id: 184, title: '10.30 - Responding To The Call of God - Gospel Encounter', keyScripture: '', summary: '', driveId: '1A2eaI2l4-B8hD2B7Ha4bLpdrid4_-77w' },
  { id: 185, title: '11 How to Become a Spiritual Christian Part 3', keyScripture: '', summary: '', driveId: '1pZZX8EyuYbDU6fByK5HjGvC616SI2OPs' },
  { id: 186, title: '11.', keyScripture: '', summary: '', driveId: '1Qg7t54KcbiHjY4NpcXoRoB6XzmOWYhaS' },
  { id: 187, title: '11.03 - Birthday Prayer', keyScripture: '', summary: '', driveId: '1E6b0Jn12RRid6ZJ9kiKiNGAxnP1h6GIO' },
  { id: 188, title: '11.03 - How to Become a Mature Christ', keyScripture: '', summary: '', driveId: '1ZhGt2LlYVTT5f0m3zY4uLDw00746W1ob' },
  { id: 189, title: '11.06 - ABMTC - Jesus Christ Son Of M', keyScripture: '', summary: '', driveId: '1SbfBgMn2wQs1p_KYzlU4jZlkm_vYXLt8' },
  { id: 190, title: '11.06 - Seek Ye First the Kingdom', keyScripture: '', summary: '', driveId: '18MuDbxOgB_756W9Js2SNOl9bS3VzJX-B' },
  { id: 191, title: '11.13 - Redeeming the Time - Three Nights of Your Life', keyScripture: '', summary: '', driveId: '1R5Sbs9_YlN1n0Ls84PYnVWa0UN1cr5dG' },
  { id: 192, title: '11.17 - How to Become a Mature Christ', keyScripture: '', summary: '', driveId: '1R8MtEZ7fHMr5TdTj-rwQQjmGwC0Nie3W' },
  { id: 193, title: '11.20 - The Assembling of The Saints Pt. 1', keyScripture: '', summary: '', driveId: '1bs98mrP0G76AkD3hFIjMugxc-emYE5WO' },
  { id: 194, title: '11.24 - Those Who Forget', keyScripture: '', summary: '', driveId: '1VrwLG3bofYHMmBYrf9OAk1JGgzOeDFPm' },
  { id: 195, title: '11.27 - Proton and Relationship - Gospel Encounter', keyScripture: '', summary: '', driveId: '1KZuu0IaTJnHp3rORuOa7tVNKudo1pgdJ' },
  { id: 196, title: '11.27 - The Assembling of The Saints Pt. 2', keyScripture: '', summary: '', driveId: '1jYrDtMDv0fglnJv4aufc2dUPfMjUeh4B' },
  { id: 197, title: '12 How to Become a Spiritual Christian Part 4', keyScripture: '', summary: '', driveId: '1zRhE0G6N8LQiAWRcorlk29MMq9rsZWKy' },
  { id: 198, title: '12.', keyScripture: '', summary: '', driveId: '1khHfroI6pssaz9Vx-qUZ7f1OWWakgfFE' },
  { id: 199, title: '12.08 - Why Philip Preached Christ', keyScripture: '', summary: '', driveId: '1cPMRkMudW_GpzM8bn0Osdr2nUY1m39-S' },
  { id: 200, title: '12.11 - My Father, My Father - Types of Fathers', keyScripture: '', summary: '', driveId: '10ut6O3DxukWJsrN6xe7g65erB39vCqw2' },
  { id: 201, title: '12.11 - Proton and Our Faults - Gospel Encounter', keyScripture: '', summary: '', driveId: '1CPe6xLaNhP9yseklo72CBNKXjHUUAnjW' },
  { id: 202, title: '12.11 - The Assembling of The Saints Pt. 3', keyScripture: '', summary: '', driveId: '1NwW2dphYTLJSk7Pn7naBwuj07WH_7OfM' },
  { id: 203, title: '12.12 - Three Strategies fo', keyScripture: '', summary: '', driveId: '1BCTq0Mj5Zn6MU0wnXFkKIxULu6LYjyWt' },
  { id: 204, title: '12.12 - Three Strategies for an Effective Quiet Time - Gathering Service', keyScripture: '', summary: '', driveId: '1WCabyYcQ0fudTYatI7OtiEsIfgSYAEcr' },
  { id: 205, title: '12.15 - Wise as Serpents', keyScripture: '', summary: '', driveId: '17N6EKkA9YyWeL7i42R1PytywbYJP4cge' },
  { id: 206, title: '12.22 - Humility and Pride', keyScripture: '', summary: '', driveId: '1AoGm6-HCYMgogtoJMsJ3YlEZLBrGJwN2' },
  { id: 207, title: '12.29 - Thanksgiving', keyScripture: '', summary: '', driveId: '1S3XNSxwxCRKQ-TprrmorE7RtCJ2jEBER' },
  { id: 208, title: '13.', keyScripture: '', summary: '', driveId: '131e0MYKtQGnsv0Qbh-CPFByUU6OF4h2u' },
  { id: 209, title: '14.', keyScripture: '', summary: '', driveId: '1crbxOc40DuBz_T3-u-41o1tl8w0WwpXG' },
  { id: 210, title: '15.', keyScripture: '', summary: '', driveId: '11MtTVLxp4kItU6ynXMo9kaBygha1F_pb' },
  { id: 211, title: '16.', keyScripture: '', summary: '', driveId: '195phNwfy88uZ4SxUsexGwpB42h1sq1rb' },
  { id: 212, title: '17.', keyScripture: '', summary: '', driveId: '13CH2W2v-r0v5yl_r940Fycf06PcDVL12' },
  { id: 213, title: '18.', keyScripture: '', summary: '', driveId: '1visw7Z9OGHkYheR_PM33cCqTcdwbaTrb' },
  { id: 214, title: '19.', keyScripture: '', summary: '', driveId: '1ffu91mf17A4iJzdAP4uxquvdFR3cefsq' },
  { id: 215, title: '2.', keyScripture: '', summary: '', driveId: '1MMeBzaIxRB58OwWHQ4MrQj5I0qrMI8Ig' },
  { id: 216, title: '20.', keyScripture: '', summary: '', driveId: '1RGEmU89aVSF8ByHLen68PAiu1loPA6l_' },
  { id: 217, title: '2017.01.22FLC_Bebelos_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1PRYFUSeqDYYQ-PRcPzuQPBCYPCtwt4LM' },
  { id: 218, title: '2017.01.22FLTC_The Art of Following_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1f1U81pXtkTbGljOvzByGyB0LXr51ByQ0' },
  { id: 219, title: '2017.02.19FLTC_Loyalty and Disloyalty (Critical Stage)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1bV-kIZLNKUZVRDGQxNZbgTOHADot4nh0' },
  { id: 220, title: '2017.03.05FLTC_Reasons Why We Must Be 1000 by December_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1nkEKotDQNCNtbN1GZI5Y4pilsOcYLTbx' },
  { id: 221, title: '2017.03.12FLC_HYPService_Honour Your Prophet_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1bFuygr6CB3jyj0Pt9xKjiFoaSoWn7LxK' },
  { id: 222, title: '2017.03.12FLTC_Why We Must Have a Mega Church_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1HfKk54cLU9BhXKbUcXZ1JVUUzD0EJ_oj' },
  { id: 223, title: '2017.03.19FLC_In the Atmosphere of War_Ps Joshua Heward-Mills.output', keyScripture: '', summary: '', driveId: '1SD81PTVP2jiBbvJlXso25aGkoaq54Xdv' },
  { id: 224, title: '2017.03.19FLTC_Why We Must Build a Mega Church (Jesus Building Project)_Ps Joshua Heward-Mills.output', keyScripture: '', summary: '', driveId: '1J84GoMup8rq0OLGtwSmCwrU4kK4fxsSY' },
  { id: 225, title: '2017.04.02FLTC_Reasons Why God Wants You to Experience Suffering (Losing, Suffering, Sacrificing, Dying)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '18LLbjnItXkkxZ5cvqbwSRXB3HBrdpGi8' },
  { id: 226, title: '2017.04.09FLTC_Why God Wants You to Suffer (Losing, Suffering, Sacrificing, Dying)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1hi-GfqY90i3zMXaPiDnklafQJp_qImP2' },
  { id: 227, title: '2017.04.16FLTC_The Fellowship of His Suffering (Losing, Suffering, Sacrificing, Dying)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '18j8J7ERI4fdHAkv7wmkEKBNc9Vstnh5v' },
  { id: 228, title: '2017.04.23FLTC_Why God Wants You To Suffer_Pt.2(Losing, Suffering, Sacrificing, Dying)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '14YdlxqsUzvUDXuZa8DhRoMrB64VsZUsz' },
  { id: 229, title: '2017.04.30FLC_Those Who Accuse You Pt.1_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1BgjPXzaZGg0lk8HIJLc0T-R6MDO-qiOX' },
  { id: 230, title: '2017.04.30FLTC_Reason_s Why God Wants You to Experience Suffering Pt.2 (Losing, Suffering, Sacrificing, Dying)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '17AkyBRXP75wg9KnRUr6n4c_3UHQOmsyG' },
  { id: 231, title: '2017.05.07FLC_Those Who Accuse You Pt.2_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1QTV8kiSL4IpxWBkelqtULg_iseslH6l6' },
  { id: 232, title: '2017.05.07FLTC_Types of Accusations(Those Who Accuse You)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1NsxBi-X56rYD4ZuLKiU7N7EO2QFpZBms' },
  { id: 233, title: '2017.05.14FLTC_You and Your Prophet_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1idyIFremahmEFTWhmgd8aw1msLR1dLSe' },
  { id: 234, title: '2017.05.21FLTC_God_s Letter to Town Church', keyScripture: '', summary: '', driveId: '1yJdSOe5jLjIdZkbewfWqK29ymjzWbLMs' },
  { id: 235, title: '2017.05.28FLTC_God_s Letter To Town Church Pt.2 (Grace and Peace)_Bishop Dag Heward-Mills', keyScripture: '', summary: '', driveId: '1nsyffaey6Ys0jKqGAiuKoyhe0IrLut32' },
  { id: 236, title: '2017.06.04FLTC_The Four Types of Wisdom_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1ZhxMN4nFADK1yA-m7tay4rTh-hUwC9n2' },
  { id: 237, title: '2017.06.11FLTC_The Art Of Following David(The Art Of FOllowing)', keyScripture: '', summary: '', driveId: '1h2LE-jz1H0n4P9HQ8fiIIz03V6rrcOnJ' },
  { id: 238, title: '2017.06.18FLTC_The Art of Following Pt.2(The Ability to Recognise Spiritual People)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1tFv0o0yenfYKx4dCDW47Wn0R_xEmKm3Y' },
  { id: 239, title: '2017.06.25FLC_The Wisdom of the Serpent(Wise as Serpents)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1Ph_gaeJIKCeD12t0G9zn0votoAvi-gcO' },
  { id: 240, title: '2017.07.02FLTC_Formula for Humility Pt.1(Four Types of Proud Speakings)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1yPkm2fngA6uIOWkkVXwwcoypN6IxCHtL' },
  { id: 241, title: '2017.07.16FLTC_Formula for Humility Pt.3(Diagnosing Types of Proud Speaking)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1o-HiAjkmX6dOJie1CnStKJptPn7HAqaw' },
  { id: 242, title: '2017.07.30FLTC_120 Reasons Why You Must be a Soul Winner_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '19KLk4vczI3Q1jBzYU7gwce1Rf1Ot6fV3' },
  { id: 243, title: '2017.08.06FLTC_Those Who Are Ignorant', keyScripture: '', summary: '', driveId: '1JBatBNIH0reL00rt1m7H4n3X1uSBquk0' },
  { id: 244, title: '2017.08.20FLC_Tell Them (Without the shedding of Blood)', keyScripture: '', summary: '', driveId: '1vv225WnJCQDPAYKUbeYBgx0aGno1Tr-P' },
  { id: 245, title: '2017.08.27FLC_Tell Them Pt. 2 (The Love Of Jesus Christ)_Pastor Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1AIl4o-th49qNDfMaR4YhgVHW98quXL4C' },
  { id: 246, title: '2017.08.27FLTC_Thos Who Are Ignorant Pt.3', keyScripture: '', summary: '', driveId: '1DtNzrfGSNurvpiLT7ewDgWH1DlNJkQqk' },
  { id: 247, title: '2017.09.03FLC_Tell them pt.3', keyScripture: '', summary: '', driveId: '1dE-z51paD98aEBfQoWBoMKMNck-55PWj' },
  { id: 248, title: '2017.09.03FLTC_Proton Introdurction Pt.1_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1yUrf1oZWW8SZBE1MntBlOtNizSJZip9v' },
  { id: 249, title: '2017.09.10FLTC_Your Prophet and Your Miracle_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '146mVo3S3q8KJwutSpJ5Y1YoKElpCitGR' },
  { id: 250, title: '2017.09.24FLC_The Disguises of the Prophet_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1rFj3uy9s8MHW6wm2haUTZbN3pmPfYbli' },
  { id: 251, title: '2017.10.01FLTC_The Prophets Honour_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1Cppi7Uhr-ZjK_Yp9rhG7d978oh7vmX77' },
  { id: 252, title: '2017.10.08FLTC_The Mystery of Tithing', keyScripture: '', summary: '', driveId: '11Rot5s4n6j_Ky7NRLkb0ulm3v8T763-D' },
  { id: 253, title: '2017.10.15FLTC_Bearing Fruits (Diligence)_Ps Joshua Heward-Mills', keyScripture: '', summary: '', driveId: '1mgDx3CpD0OXQHLm83pSAciaZFUlP-scP' },
  { id: 254, title: '2017.10.22FLTC_Pastor Joshua Heward Mills_Bearing Fruits', keyScripture: '', summary: '', driveId: '1MSeAqdXSDWNcpvBbdRrqEM5DFCk7lCCG' },
  { id: 255, title: '2017.10.29FLTC_Pastor Joshua Heward-Mills_Bearing Fruits Pt.3', keyScripture: '', summary: '', driveId: '1nM9tpb18j_7ryYoRLLxbDyzxkAinUr_Z' },
  { id: 256, title: '2017.11.12FLTC_Pastor Joshua Heward-Mills_Why You Must Be A Part Of A Mega Church', keyScripture: '', summary: '', driveId: '1w1omkyRvPXkT5FJhkRpFDetsTG7aDTkL' },
  { id: 257, title: '2017.11.26FLTC_Why You Must Be Part Of A Mega Church Pt 3', keyScripture: '', summary: '', driveId: '1BhUvxiu8W1J-aA5gLpNqHSx9yow3R4jx' },
  { id: 258, title: '2017.12.03FLC_How To Be A Humble Minister Like Jesus Pt. 1', keyScripture: '', summary: '', driveId: '1tj3lVJaXOH-u4ugXEZXX5F3MY3N7wmoT' },
  { id: 259, title: '2017.12.03FLTC_What It Means To Become A Shepherd', keyScripture: '', summary: '', driveId: '1PPPhmE6knwlbtJJIu0IPleSt-GbkODVJ' },
  { id: 260, title: '2017.12.10FLC_How To Be A Humble Minister Like Jesus Pt. 2', keyScripture: '', summary: '', driveId: '1WGqgb1zIQa177Y2mF9gNRue3os-S2CN_' },
  { id: 261, title: '2017.12.10FLTC_What It Means To Become A Shepherd Pt. 2', keyScripture: '', summary: '', driveId: '1Wz_pxTkg5Z6pVmQxDtTiuAFlOshh2GEJ' },
  { id: 262, title: '2017.12.17FLTC_What It Means To Become A Shepherd Pt. 3', keyScripture: '', summary: '', driveId: '1Z4bZPSUCD4QIIZ0gEHaDl-pWbDOtlqHR' },
  { id: 263, title: '2017.12.24FLTC_What It Means To Become A Shepherd Pt.4(Will It Follow Me)', keyScripture: '', summary: '', driveId: '1BJ6MJ6-o6Q0GMub0ChprDGXpBAJJ8nYQ' },
  { id: 264, title: '2017.12.31FLTC_Be Ready For A Long Fight', keyScripture: '', summary: '', driveId: '1txI0v9rNK2CLBTw5QucZO1yPfjho4E6z' },
  { id: 265, title: '2018.03.18FLC_ - The Supernatural Abilities of The Blood', keyScripture: '', summary: '', driveId: '10KqAbJL_ug2Uz8OVcn_w6U2pNvgfXxO2' },
  { id: 266, title: '2018.04.22FLC_ - 10 Things FirstLove Church Mu', keyScripture: '', summary: '', driveId: '1A5MsRNrov6a_v1lB2TgTKq52Xvouky9g' },
  { id: 267, title: '2018.07.01FLC_ - Many Are Called', keyScripture: '', summary: '', driveId: '1V2P9AenaRrE_jbsVPP4nVVFTzHV5sx37' },
  { id: 268, title: '2018.08.26FLC_ - Sweet Influence of the Holy S', keyScripture: '', summary: '', driveId: '17ch6jub0fdYY3GUjyN5ItEuZGyLp38pI' },
  { id: 269, title: '2018.09.02FLC_ - The Art of Following', keyScripture: '', summary: '', driveId: '1pwHHvcSrcU_-bzyFmZq1x740ozDlhTde' },
  { id: 270, title: '2018.09.30FLC_ - Carefully Choose Your Mentor', keyScripture: '', summary: '', driveId: '1JLNhp7EVNglEFl7y9fdcn_iBdOel6rfC' },
  { id: 271, title: '2018.10.07FLC_ - Honour Your Prophet', keyScripture: '', summary: '', driveId: '1WEvFDnOQZ6Pz-IqYU5oJY7VEVi28HDHN' },
  { id: 272, title: '2018.10.14FLC_ - Honour Prophet and Prosper', keyScripture: '', summary: '', driveId: '1iM6soG2G9CM3F7IieENOGq7ZBz2fQnps' },
  { id: 273, title: '2018.10.28FLC_ - Strong Christian (How to beco', keyScripture: '', summary: '', driveId: '1JQp3OIVZUosD9nufQkb3e9zEc3BXCkMr' },
  { id: 274, title: '2018.11.04FLC_ - The Strange Woman', keyScripture: '', summary: '', driveId: '1Pab3-ObchVDXUfzf61ev1nA8CI5RCN5g' },
  { id: 275, title: '2018.11.11FLC_ - Peace The Umpire (How to Be I', keyScripture: '', summary: '', driveId: '1JGP7UFcPxMBHaQoeX0kBdDnKXLfaQNU8' },
  { id: 276, title: '2018.12.02FLC_ - Powerful Effects of The Quiet', keyScripture: '', summary: '', driveId: '1NAzDK_bDnViEqv0pdWJET_KoPXrWuKAP' },
  { id: 277, title: '2018.12.09FLC_ - Remember Lots Wife', keyScripture: '', summary: '', driveId: '1-iXlIV6aOqViVarQ8bx6eiGvDtUbcF48' },
  { id: 278, title: '2018.12.16FLC_ - Temple Blessings', keyScripture: '', summary: '', driveId: '1ZE3rXg3GId8LXW9Iv0AXY8P5suGdscIZ' },
  { id: 279, title: '2018.12.23FLC_ - Avoid Shallowness Through the', keyScripture: '', summary: '', driveId: '1xxG26PYSSAOjx1ytnUzKoYnrK5-6gIh2' },
  { id: 280, title: '2020.01.05FLTC_Make Yourself Saviors of Men', keyScripture: '', summary: '', driveId: '1unM1vT70jK3YcT3LbQgPfAJy14bevJSr' },
  { id: 281, title: '2020.01.12FLTC_Make Yourselves Saviours of Men Pt. 2', keyScripture: '', summary: '', driveId: '1SggWDFH8mJ5C6zFaoIJMruNp1UmuzE7i' },
  { id: 282, title: '2020.01.18_FLCC_KEEP THE MUNITION', keyScripture: '', summary: '', driveId: '1fTe_DalDJ8zJn0K-youMJHGR6J75wT9m' },
  { id: 283, title: '2020.01.19FLC_Make Yourselves Saviours of Men(Matthew)', keyScripture: '', summary: '', driveId: '1zD5m3JGP5VodJbNqOXLUvB7y5D9ldaWp' },
  { id: 284, title: '2020.01.19FLTC_Make Yourselves Saviours of Men(James)', keyScripture: '', summary: '', driveId: '1QE8oXF2xLM1CSdsfFgkqpimBzN4xCdKD' },
  { id: 285, title: '2020.01.25_FLCC_Quiet Time', keyScripture: '', summary: '', driveId: '1a5tEgrwiR1QnIOpLHjxLiVtCP6W7ktm0' },
  { id: 286, title: '2020.01.26FLC_The Great Commission from the Book of Acts', keyScripture: '', summary: '', driveId: '1lbg1ejznvXpBhbz4sq5PSYHldXupxPQ6' },
  { id: 287, title: '2020.01.26FLTC_Make Yourselves Saviours of Men Pt. 4 Great Commission.', keyScripture: '', summary: '', driveId: '1N1hVLA9V9LfdCSur4CDsaq6WXBz1UFeR' },
  { id: 288, title: '2020.02.01_FLCC_STEPS TO AN EFFECTIVE QUIET TIME 2', keyScripture: '', summary: '', driveId: '17TLC1Fzn0IoKzok4wzfkQKI_8HVTynN5' },
  { id: 289, title: '2020.02.02FLTC_Make Yourselves Saviours of Men. Pt. 5', keyScripture: '', summary: '', driveId: '1CyfuJmwvQyJKd5kEC8VDWhg09-VoCj20' },
  { id: 290, title: '2020.02.05.Kotobabi_WITHOUT ME YOU CAN DO NOTHING', keyScripture: '', summary: '', driveId: '1Rn_yaSfUCesEqIFBeYG79UJmS5DOheme' },
  { id: 291, title: '2020.02.08_FLCC_How to be a Strong Christian( The Prevailing Word of God).', keyScripture: '', summary: '', driveId: '1wViDAdGIecTUbqTVVZNzGE0nkerKKR7Z' },
  { id: 292, title: '2020.02.09FLTC_Make Yourselves Saviours of Men( The Great Commission according to Jude).', keyScripture: '', summary: '', driveId: '1NvOU-AbSvcUmFXJzQwgNjd-o9sNGrK5s' },
  { id: 293, title: '2020.02.11.KORLE-BU_DEMONS AND HOW TO DEAL WITH THEM', keyScripture: '', summary: '', driveId: '1nEZ5JNFwLv4ZU-v0OhBd-n4DCV8vb3rt' },
  { id: 294, title: '2020.02.11_WIS_Devils and How to deal with them', keyScripture: '', summary: '', driveId: '1Jr17IMJ9Av6NM94p44-CHZITIvdY-c-B' },
  { id: 295, title: '2020.02.12_ABMTC_Your Faith Your Life', keyScripture: '', summary: '', driveId: '1iJsCqz0eT2L-rvaB3JPgxVU8pM-zBvHe' },
  { id: 296, title: '2020.02.13_UPSA_Secrets of a Directed Path', keyScripture: '', summary: '', driveId: '1ZKjsoTwv73pH_6L7S63NGgGD0TAdN2mT' },
  { id: 297, title: '2020.02.22_FirstLove Houston_Your Personal Encounter with God', keyScripture: '', summary: '', driveId: '1mj3ztkwiqwRUL09bM0Ol7_4nhzhX3DED' },
  { id: 298, title: '2020.03.06FLC_Birth Right', keyScripture: '', summary: '', driveId: '1B1Bk79Zp4GMvj9xisYRYMyX_IcJ1YC_d' },
  { id: 299, title: '2020.03.07_FLCC_Fortify Thy Power Mightily', keyScripture: '', summary: '', driveId: '1VYKRYeRMYaT6KtYVA2UIpZSbqP5pgqhQ' },
  { id: 300, title: '2020.03.08FLTC_The Sweet Influences of the Holy Spirit. Pt. 1', keyScripture: '', summary: '', driveId: '1wF1AdYog-pcJ3z-Fc78o8ZvTIbRwyffM' },
  { id: 301, title: '2020.03.14_FLCC_The Sweet Influence of the Holy Spirit on your Knowledge of God', keyScripture: '', summary: '', driveId: '1mveV_ondhftOs32uDrg4XfoEOUeWOkGJ' },
  { id: 302, title: '2020.05.19_FLCC_How Different People Were Called ', keyScripture: '', summary: '', driveId: '1IGK8U6XthW-8vpKiO738kGdyYiXtMSCK' },
  { id: 303, title: '2020.06.02_FLCC_Characteristics of Called People', keyScripture: '', summary: '', driveId: '1Vjw4GnuzEAsdzGW_zB_gs5nIMeO1vXO9' },
  { id: 304, title: '2020.06.09_FLCC_The Limitations of an Individuals Calling', keyScripture: '', summary: '', driveId: '1iGYsXvyUjt2sXIgLs7aLcOTMDIPv8wk1' },
  { id: 305, title: '2020.06.16_FLCC_How God Monitors your Works', keyScripture: '', summary: '', driveId: '1wboguijPqeWf0n7eN9KezZN3wIKZDH_s' },
  { id: 306, title: '2020.06.23_FLCC_Barren Because You Are Blind to Hell', keyScripture: '', summary: '', driveId: '1T05Ict6tYGURkWQQontKiJAyie2n9x2F' },
  { id: 307, title: '2022.04.30FLCGES_The Art of Leadership (Everthing Depends on Leadership)', keyScripture: '', summary: '', driveId: '1lDNYs65OW0t2l1PUBNNMijSP6LdvEP4R' },
  { id: 308, title: '2022.06.04 AOL - See Ahead and Prepa', keyScripture: '', summary: '', driveId: '1Y3lFyULNIL6FN0Evs5ygFy5JCR_0Ka7B' },
  { id: 309, title: '2022.06.11 AOL - Give People Hope', keyScripture: '', summary: '', driveId: '1x_FKeIbnENERhQm8TieK33ssVby2WIEm' },
  { id: 310, title: '2022.07.09 Job and Others', keyScripture: '', summary: '', driveId: '1vfFFfMnpZ0KL8upM9rYhnRySpm9GEQNu' },
  { id: 311, title: '2022.07.10 Why You Can Become A Shep', keyScripture: '', summary: '', driveId: '1RBVgLs-YMCw6sui-3i23NYZWH6qu9E_l' },
  { id: 312, title: '2022.07.15_FLLC_What It Means for the Sheep To Have No Shepherd', keyScripture: '', summary: '', driveId: '1VgooXiSZc21z-rppBH_OqGvoVdUIPK3N' },
  { id: 313, title: '2022.07.17FLC_How to Become a Shepherd Part 2', keyScripture: '', summary: '', driveId: '1LF4eAk6XCbt1qlAa1IQ38e4H4HtjeISd' },
  { id: 314, title: '2022.07.31FLC_Take Up the Spiritual Burden', keyScripture: '', summary: '', driveId: '1BAPBiLS1FTjPSbhCln-X_DfaGuPFieiI' },
  { id: 315, title: '2022.08.06FLCGES_John 3  16', keyScripture: '', summary: '', driveId: '1wLznqRmO6mLvRg-ijUcuabNK9Ui2X0Qt' },
  { id: 316, title: '2022.08.16_FLC_Make Yourselves Saviours of Men Part 2', keyScripture: '', summary: '', driveId: '1ayuxGBHPrCH9siU39Bd3_cMfWoaDdg6u' },
  { id: 317, title: '2022.10.24 - UK - Q&A UK Leaders small', keyScripture: '', summary: '', driveId: '1sY1F1Vl6qgg1XEGhZ7BiqhK8VBS28cLH' },
  { id: 318, title: '2022.11.05_FLGES_He that Hath (A sower of seeds) 2', keyScripture: '', summary: '', driveId: '1KionkDrCVzYWk3JhgXQXnR7pIZ1LkSNL' },
  { id: 319, title: '2022.11.16_ABMTC_Keys to Becoming a Good Shepherd', keyScripture: '', summary: '', driveId: '163Sd1XyFqP336Fe_ki12gKj9HDFOvDgq' },
  { id: 320, title: '2022.12.04FLCES_Reasons Why First Love Church Must Be a Mega Church', keyScripture: '', summary: '', driveId: '1ZpyUbhsTKWeLRkCohW6HrzD76C2Qlfft' },
  { id: 321, title: '2022.12.11_ABMTC_How to be in The Perfect Will of God', keyScripture: '', summary: '', driveId: '1eOBrHPiGXwDbH281rc_l_HV60Dr71uPS' },
  { id: 322, title: '2022.12.11_FLCES_Types of Commitment', keyScripture: '', summary: '', driveId: '12aPQJkXOpaSsun6OKJFWayJ_h_ERuL1I' },
  { id: 323, title: '2023.01.07_ABMTC_Attempt Great Things for God', keyScripture: '', summary: '', driveId: '1r_uIYk5D6Q3qJS3WUtQP5-GiQ1IekD8w' },
  { id: 324, title: '2023.01.08FLCES_Attempt Great Things for God', keyScripture: '', summary: '', driveId: '1MAGU-sM3LF_E4O6ADga6xrdEqXphWahB' },
  { id: 325, title: '2023.01.08_FLCHGE_Attempt Great Things for God', keyScripture: '', summary: '', driveId: '1PB_aoNhQRngLtuqqOmrPlnlFC8dIK2s9' },
  { id: 326, title: '2023.01.14_FLCGES_Formula For Humility Part 1.', keyScripture: '', summary: '', driveId: '1qzTdn514Ivmb2YSzPu4Uc_hHw2ED_5iP' },
  { id: 327, title: '2023.01.15FLCES_Reasons Why Everybody Must Pray', keyScripture: '', summary: '', driveId: '1mXTmV9-M1Puj1us_Y91irIfVTyMTkMu1' },
  { id: 328, title: '2023.01.15FLCGHE_Prayer', keyScripture: '', summary: '', driveId: '1oyt3AshrmxKfyB3wg3hIsw6lFZDdVddY' },
  { id: 329, title: '2023.01.21_FLCGES_Formula for Humility Part 2', keyScripture: '', summary: '', driveId: '1UCtV6UByCIaEd6ayNU6sD9EzlVEBe_Mc' },
  { id: 330, title: '2023.01.22FLCHGE_How You Can Receive The Holy Spirit', keyScripture: '', summary: '', driveId: '1npR1XdVyylrpXQzhheRInWGsU6lRgGUO' },
  { id: 331, title: '2023.01.22FLC_The Mystery of Prayer', keyScripture: '', summary: '', driveId: '1Rs_k53KvdQ6kwtCw-ymSV2zf6qDWiQu3' },
  { id: 332, title: '2023.02.08_UPSA_The Prodigal Son', keyScripture: '', summary: '', driveId: '19cneTCaVFjwIrWj_8cGTMN_z4YvKL9CM' },
  { id: 333, title: '2023.02.09_WIS_The Truth', keyScripture: '', summary: '', driveId: '1qooh62VeanDPG5NgQOd5x1zMj8f903ek' },
  { id: 334, title: '2023.02.10_ATU_By His Stripes', keyScripture: '', summary: '', driveId: '1pfHmPEKzA6XmBwiliWx4aH8kiyi4N4WU' },
  { id: 335, title: '2023.02.17_DANS_Christ in you, the Hope of Glory', keyScripture: '', summary: '', driveId: '1ES1I3WEzpcr7iLJ7rwvnnAOWleLwU0NS' },
  { id: 336, title: '2023.02.21_KWAB_Your faith has made you whole', keyScripture: '', summary: '', driveId: '1AY_tFyZwlPkuPRxYRcDmzWaoXuVdCSo1' },
  { id: 337, title: '2023.02.22_FOSTER HOMES_The works of God', keyScripture: '', summary: '', driveId: '18acuWcHaPUJKef6vhxdQJaqk4BBDaZoi' },
  { id: 338, title: '2023.02.23_MADINA_Thou son of David, have mercy on me', keyScripture: '', summary: '', driveId: '1tJjEJgtLgwSSAbtn9m0Xjs-it5w2ERnX' },
  { id: 339, title: '2023.02.24_KORLE-GONNO_Jesus will do you good ', keyScripture: '', summary: '', driveId: '1Hgom6ZbZVcNg6E2ZTtd8olqciEI-U_Sc' },
  { id: 340, title: '2023.02.26_LEGON_Almost', keyScripture: '', summary: '', driveId: '1t3PpgtAzG-PrFFC-k2YjPCYJ3LAzORK0' },
  { id: 341, title: '2023.06.18_FLHGE_What You Must Know About Salvation', keyScripture: '', summary: '', driveId: '13MQ4UGe31g8407hsadRyweSRUZHtAiFs' },
  { id: 342, title: '2025.07.20FLCHGE_POISON', keyScripture: '', summary: '', driveId: '1dNu9UUB6mIHRnVJnjhPWtsswhbLJTP5y' },
  { id: 343, title: '2025.07.30 Taking Heed', keyScripture: '', summary: '', driveId: '15G-WofRdwZ4rNWdUoso-JMPPlsmvPgzI' },
  { id: 344, title: '2025.08.01 Change', keyScripture: '', summary: '', driveId: '1Yy9cr1NnQjFq5iolgN7Bs1EvNwX_VtrL' },
  { id: 345, title: '21.', keyScripture: '', summary: '', driveId: '11FVW3cPhvNTRLtkXoTyNVl0f2sr_i07h' },
  { id: 346, title: '22.', keyScripture: '', summary: '', driveId: '1M26H9fAt5Cb1kswXV4bErr_DAIVluVK1' },
  { id: 347, title: '23.', keyScripture: '', summary: '', driveId: '1oZmwO10XV-A9QxnRREUUlOnFca4Ew3oV' },
  { id: 348, title: '24.', keyScripture: '', summary: '', driveId: '18zXQvfG6mR0VTMGP49-whVLLqV4VdL-F' },
  { id: 349, title: '25.', keyScripture: '', summary: '', driveId: '1CUNVbIRWHJ79Q6hva-RB_zPNa__hdB5o' },
  { id: 350, title: '26.', keyScripture: '', summary: '', driveId: '1g2CZemrapeBY3LIwOfE1iRtwsz1cyfYU' },
  { id: 351, title: '27.', keyScripture: '', summary: '', driveId: '1sGSTLFNbJMUbrdPtSkOVvEFulPFGyYGR' },
  { id: 352, title: '3.', keyScripture: '', summary: '', driveId: '12IOuIvQSxhC_I3XNKdp6omGxNu1SaKtb' },
  { id: 353, title: '3_06_26_SAT_How a Spiritual Son Develops into a Shepherd', keyScripture: '', summary: '', driveId: '1UmCmeyKP4tMYhVuYgRlxlQ-mm9uvec1Q' },
  { id: 354, title: '4.', keyScripture: '', summary: '', driveId: '1o5V4J1gP1hbbSBe6BXfS6Bjg9fUb6R-7' },
  { id: 355, title: '5.', keyScripture: '', summary: '', driveId: '1Sc1vMOY_rX2kWaOT37oEWzaNPJh7Qpke' },
  { id: 356, title: '6.', keyScripture: '', summary: '', driveId: '1Zpj58HTL3GWjFzeZtK2Aj7eaa1VEl7tG' },
  { id: 357, title: '7 Steps To Honoring - The Experience', keyScripture: '', summary: '', driveId: '1cwanPJ-_FMV91yQKnhIc5XGQJn_oJPAU' },
  { id: 358, title: '7 Steps To The Anointing - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1mHbnDVu1p9Eal6MinKdON8cBjZDALpUa' },
  { id: 359, title: '7 Steps To The Anointing - The Experience', keyScripture: '', summary: '', driveId: '1-83_8dePEB1_fZPu5Ybnrbbwkv0wrDga' },
  { id: 360, title: '7.', keyScripture: '', summary: '', driveId: '1P5u9AXX0E7LV60Xr-gC716hSMsrAib4a' },
  { id: 361, title: '8.', keyScripture: '', summary: '', driveId: '12L9AXr5CtE2pC4xCO6a734HUaaVc1khu' },
  { id: 362, title: '9.', keyScripture: '', summary: '', driveId: '1Jw16qbAWvV3nLo1ugIgk4TSfwIkiQ06n' },
  { id: 363, title: 'AUDIO-2025-10-29-23-22-45', keyScripture: '', summary: '', driveId: '1SIB7Yl0Y_t3NFX3x8qpore2pL63Ou-dl' },
  { id: 364, title: 'AUDIO-2025-12-07-04-29-42', keyScripture: '', summary: '', driveId: '1B21PaKp1oe2myl9P1k8p4LhPThZg49Rj' },
  { id: 365, title: 'Art of Hearing - City Church - October 29th ', keyScripture: '', summary: '', driveId: '1aRoyIhU0ann9kUzl8wberr06KGx4c_zq' },
  { id: 366, title: 'Atmosphere Part 1 - Do You Know You_re A Tree', keyScripture: '', summary: '', driveId: '1-pTbp43-UaRpSLlj4g_O2u6u6ikW_6Wc' },
  { id: 367, title: 'BJosh First Service FB Live', keyScripture: '', summary: '', driveId: '1LgeRD2VX6lWuFV6UcF2ao2euikKcV-7R' },
  { id: 368, title: 'Bjosh FB Live Midweek Service - April 15th ', keyScripture: '', summary: '', driveId: '1IcJpMP4yn3GkrGiwCO75KbyzOQOvTz64' },
  { id: 369, title: 'Church Growth Pt. 1 - Reasons Why We Must Have A Mega Church - The Experience', keyScripture: '', summary: '', driveId: '1bpsYGMpSPg6km1DbwAbKiNYY79v7TsPI' },
  { id: 370, title: 'Church Growth Pt. 2 - How Lay People Will Help To Bring Church Growth - The Experience', keyScripture: '', summary: '', driveId: '1H2G1tfao_YSQWuKZ2yFHvGHTl0_QoJPv' },
  { id: 371, title: 'Church Growth Pt. 3 - Anagkazo, Biazo, Anadeia - The Experience', keyScripture: '', summary: '', driveId: '1-2oxU9B1ICOfoMftEiiAokGJ_mXobNDz' },
  { id: 372, title: 'Church Growth Pt. 4 - Anagkazo and Church Growth - The Experience', keyScripture: '', summary: '', driveId: '1j4V-x9CjC7pR0z28jo5Yn4lNHVkOK0h9' },
  { id: 373, title: 'Church Growth Pt. 5 - You Shall Serve And He Shall Bless - The Experience', keyScripture: '', summary: '', driveId: '1sdjRQGVkfBzj5XuNJiqc14N1iS7ynwg7' },
  { id: 374, title: 'Church Growth Pt. I - Reasons Why We Must Have A Mega Church Pt. 1 - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '13xtM2lR5T60L6TeGx3_r-T_e9R0Sn6Zc' },
  { id: 375, title: 'Church Growth Pt. II - Reasons Why We Must Have A Mega Church Pt. 2 - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1f-meDndaJMAJnAyi0_6zr3PFwp3an6AG' },
  { id: 376, title: 'Church Growth Pt. IV - Evils That Evolve When Lay People Are Not Involved - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1aKjvLd6iyaEMcWpFat79BTpA48R77AhA' },
  { id: 377, title: 'Church Growth Pt. V - The Good Samaritan - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1rt75IOI28PcPjxJiV63t4tgniknO-4Am' },
  { id: 378, title: 'Come Unto Me - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1a9ANsUTQmWRVeKzEt4gpc3dTFFIC-nq4' },
  { id: 379, title: 'Everything By Prayer - The Flow Church', keyScripture: '', summary: '', driveId: '1iAqOSLy3xk6voD_jnRhlcds4skeikUs9' },
  { id: 380, title: 'FLJN_03.07.2026_ The Spirit of a Saved Man is Righteous and Truly Holy', keyScripture: '', summary: '', driveId: '1eYKFC2tuvRPlLt9_7DrWk7QIP_dUe1y_' },
  { id: 381, title: 'Fervent Prayer | Part 1', keyScripture: '', summary: '', driveId: '1ckz7Ce6vDrc7r14E17INCSLFaQnoVirg' },
  { id: 382, title: 'Fervent Prayer | Part 2', keyScripture: '', summary: '', driveId: '1Ie18Xxa7KMlP6dYwFt1tnvn4ZKtssyMR' },
  { id: 383, title: 'Honour For The Anointing - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1y1d6w6YiN9MTJ2Pbud0nYRXJkva7t5tZ' },
  { id: 384, title: 'Honour Your Prophet - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1VHX6Qd8KM68BwU1YxfcwKO7U5ZH36E6j' },
  { id: 385, title: 'How You Can Preach Salvation Pt. 1 - Interaction - The Experience', keyScripture: '', summary: '', driveId: '1NUA8sAH0JxUgvAo114UxuT8mpdpv5Fj9' },
  { id: 386, title: 'How You Can Preach Salvation Pt. 2 - Teaching - The Experience', keyScripture: '', summary: '', driveId: '1B_KR8xzru2PKTEOnC9k6f-r5LOMXQGJU' },
  { id: 387, title: 'How You Can Preach Salvation Pt. 3 - Visitation - The Experience', keyScripture: '', summary: '', driveId: '15buhSJl8_wAcgOWFTwdKpBATeudNYi6V' },
  { id: 388, title: 'How You Can Preach Salvation Pt. 4 - Prayer - The Experience', keyScripture: '', summary: '', driveId: '1jnZJig23zyobYyn3QJqytO69rj0uP6iJ' },
  { id: 389, title: 'How You Can Preach Salvation Pt. 5 - How To Establish People In Church - The Experience', keyScripture: '', summary: '', driveId: '11VySvb3m3ORkLFiOEPamfGsfl-_MUAyA' },
  { id: 390, title: 'How You Can Preach Salvation Pt. I - Interaction - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1VRrApgXveTc0X3eDQyb04-ILlI5Po2E6' },
  { id: 391, title: 'John 3_16 - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1h_JeNIX0uUnDZOlZbobHBE7Bz0OO9-45' },
  { id: 392, title: 'Meeting God - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1YcGXs2szXjTqPs6D2BbyRqj78N9lHZLW' },
  { id: 393, title: 'Men Ought Always To Pray - The Flow Church', keyScripture: '', summary: '', driveId: '1Hc02uJTPeNXaBOqqm61OWKK39VQLWCvL' },
  { id: 394, title: 'OMO - JHM', keyScripture: '', summary: '', driveId: '1w_YhhjU8KzEe2RNyLoR1RH8ZcPxeaEAp' },
  { id: 395, title: 'OTHERS - FirstLove Experience - Joshua Heward-Mills - 15.02.26_SAT', keyScripture: '', summary: '', driveId: '1pWsV6FhV3AAZS3OawdnBU-WaEEr6Nx_Y' },
  { id: 396, title: 'Oikodomeo (Edify) - The Experience', keyScripture: '', summary: '', driveId: '1jrzqqmzVd5gFBOITV_ZXUAhdQ5Ga3x3E' },
  { id: 397, title: 'Poison Pt. I - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1eC1JHCGv10MC7IH96nWiN8i6Bb6ZywTP' },
  { id: 398, title: 'Poison Pt. II - Lies - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1Chf_TawrjHD0cOrSsD1tvNv-hPliZurk' },
  { id: 399, title: 'Poison Pt. III - Blasphemy - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1mgCxPd125LHe4CCVMZjSk9t20iNcw2ha' },
  { id: 400, title: 'Poison Pt. IV - Expressing Doubt - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '16Yp_QlRI5qFPBM8A6UF-A0rnnF5wGHnQ' },
  { id: 401, title: 'Poison Pt. V - Talebearing & Slander - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1LLw_rPaJ4e9zaG0azt3qo2Bqrnx9M-hS' },
  { id: 402, title: 'Praying Always In The Spirit - The Flow Church', keyScripture: '', summary: '', driveId: '1UHwD1VPrRVApxryN6OJSU3d1k8mokN1V' },
  { id: 403, title: 'Role of a church member _ Nov 16, 2022', keyScripture: '', summary: '', driveId: '1xjGO1oYLzZj6ljihTk190JQRJV5VBMYS' },
  { id: 404, title: 'Seven Great Principles For A Great Change Pt. 1 - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '14nfQ_kW6DkEhkTyIHO4msvTMIi_KkgiW' },
  { id: 405, title: 'Seven Great Principles For A Great Change Pt. 2 - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1D-Nk0pEqk5JaSRjch4xgKu-bVNGHnOKW' },
  { id: 406, title: 'Seven Great Principles For A Great Change Pt. 3 - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1QjENXXEGOqnHxFWjsyfaeMFC6hGunMDh' },
  { id: 407, title: 'Swollen Sunday Pt. 1 - Why_ - The Experience', keyScripture: '', summary: '', driveId: '18P62bcQ_2gaQHCSh1iYUANLwPUTfsT3p' },
  { id: 408, title: 'Swollen Sunday Pt. 2 - We Are All Involved - The Experience', keyScripture: '', summary: '', driveId: '1k0mf0CbvvYfMcQYXoj5SdV5o2NwOq8Xw' },
  { id: 409, title: 'Swollen Sunday Pt. 3 - 1 Member, 5 Souls - The Experience', keyScripture: '', summary: '', driveId: '1RIBquvitBtj3dc9Fm9EBpmp-BWt_Xzmt' },
  { id: 410, title: 'The Art of Leadership(Dont give up on Your Source of Power)', keyScripture: '', summary: '', driveId: '1YgZhCC4zaIf3i9WAROYZaqS0ZC9L6T0B' },
  { id: 411, title: 'The Dream Church Pt. 1 - The Church That Prays Fervently In Tongues - The Experience', keyScripture: '', summary: '', driveId: '1pEsxP_2Qb2QuwX7XO6DNsXx3hQpecC5P' },
  { id: 412, title: 'The Dream Church Pt. 2 - The Church of Miracles & Manifestations - The Experience', keyScripture: '', summary: '', driveId: '1FJSi5XYqC2V1L8KN5DRuimDO7Zol6kz5' },
  { id: 413, title: 'The Dream Church Pt. 3 - A Church of Faith - The Experience', keyScripture: '', summary: '', driveId: '1uvwMQD51Nitw2j-Xn_t6BMHqJUeY4sNh' },
  { id: 414, title: 'The Dream Church Pt. 4 - The Church of Soul Winners - The Experience', keyScripture: '', summary: '', driveId: '1pMut1NhYA-JmkphZpKSqcc7yE5U9upqR' },
  { id: 415, title: 'The Four Lepers and Others', keyScripture: '', summary: '', driveId: '1ravZcXFK7RC6irhDn25u7T9QLF3JFqFp' },
  { id: 416, title: 'The Good Samaritan and Others', keyScripture: '', summary: '', driveId: '1CdqHL6tGGpYEJgs6-cNTx3bFsSDvZRpD' },
  { id: 417, title: 'The House On A Rock - The Experience', keyScripture: '', summary: '', driveId: '1WRRdOTs4vQwp1AyTfpIyxo9z_B7inBbN' },
  { id: 418, title: 'The Man With The Palsy - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1vWr6XTX9BnRATrM79X_BxvK10C6EqcE2' },
  { id: 419, title: 'The Power of Spirituality - How To Become A Spiritual Christian Pt. 1 - The Experience', keyScripture: '', summary: '', driveId: '1v4qdWhZ17NHue8uwr1OzFfXcJ2BL7r8k' },
  { id: 420, title: 'The Power of Spirituality - How To Become A Spiritual Christian Pt. 2 - The Experience', keyScripture: '', summary: '', driveId: '1fu0B0rTOgogAaraQmx20uR-X_IN0XS0U' },
  { id: 421, title: 'The Presence of God Pt. 1 - What Defines His Presence - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1-XQFynVRmMyzLFjTVPRrQPOL3EgICJRE' },
  { id: 422, title: 'The Presence of God Pt. 2 - Obedience, The Master Key To The Pressence of God - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1GiJl8vl1fRMGyqhD8df4e0x53A-4jFOO' },
  { id: 423, title: 'The Voice Of The Anointed - The Experience', keyScripture: '', summary: '', driveId: '1H3YzAq3wvGPILwUnfyvfkbf0nCub42jp' },
  { id: 424, title: 'The Well And The River - First Love Switzerland', keyScripture: '', summary: '', driveId: '1n45Jd7_TXK1rjI-Bm26QRaSznYVCqqaC' },
  { id: 425, title: 'Victory In The Backside of The Desert - Holy Ghost Night', keyScripture: '', summary: '', driveId: '1q4fbjBhwmdxCuqAssM_wQ12vUqwlcDfd' },
  { id: 426, title: 'Visitation', keyScripture: '', summary: '', driveId: '19Vg4e9rfOUvSLjRRvetevh1IIyxdiAXh' },
  { id: 427, title: 'Who Is He That Overcometh The World Pt. 1 - What Is The World_ - The Experience', keyScripture: '', summary: '', driveId: '11FgP2QqtXDDmJYjze0NXhflS4cjzd0fa' },
  { id: 428, title: 'Who Is He That Overcometh The World Pt. 2 - If This World Is Not My Home, What Is It_ - The Experience', keyScripture: '', summary: '', driveId: '13GKVHSqnPiICVteSp-DzQhCltxscMNA7' },
  { id: 429, title: 'Who Is He That Overcometh The World Pt. 3 - The Course of This World - The Experience', keyScripture: '', summary: '', driveId: '1Hw1dmLkP0b-94N7GXuFI9NJt17-hU3ay' },
  { id: 430, title: 'Why Philip Preached Christ - Holy Ghost Encounter', keyScripture: '', summary: '', driveId: '1niW2KsmKKuE9roQWv9qeNDE22dlDduDX' },
  { id: 431, title: 'Your Role As A Church Member', keyScripture: '', summary: '', driveId: '1jxFr3hNrfviGXpBJNUPfmyxqlp5CklQd' },
  { id: 432, title: 'Your Role As A Church Member - The Experience', keyScripture: '', summary: '', driveId: '12jSFfRx4yBDqmmq9SzmpRApQLieLYfFO' }
];  },
  {
    id: 5,
    title: "The Gospel in a Nutshell",
    keyScripture: "1 Peter 1:9–10",
    summary: "The salvation we freely receive was prophesied and longed for across thousands of years. The prophets searched for what we now simply possess — the greatest gift in history.",
    topics: ["salvation", "gospel", "great salvation", "cross", "prophecy", "Isaiah 9:6", "Malachi", "1 Peter 1", "salvation rally", "plan of salvation", "prophets foretold"],
    scriptures: ["1 Peter 1:9-10", "Isaiah 61:1", "Isaiah 9:6", "Genesis 49:18"],
    driveId: "1OdgQg4c4CsrZf1f4WG6dzYsoys8k0ypM",
  },
  {
    id: 6,
    title: "Why You Should Avoid Pseudo Ministry",
    keyScripture: "Ephesians 4:11",
    summary: "God gave only five ministry gifts to lead the church. True ministry is pure like the gold in Solomon's temple — anything less is counterfeit and will not carry the anointing.",
    topics: ["pastoral ministry", "five-fold ministry", "apostle prophet evangelist pastor teacher", "real ministry", "gold", "pseudo ministry", "Ephesians 4:11", "Exodus 25", "temple", "purity in ministry"],
    scriptures: ["Ephesians 4:11", "Exodus 25:1-8"],
    driveId: "1kbytiBQLm9Vzfz20k3nETTtdIqSrnEnc",
  },
];
