import { GoogleAuth } from 'google-auth-library';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import Anthropic from '@anthropic-ai/sdk';

const FOLDER_ID = '1TvUjIL9px2q29TJcu3-QW_BAqkmWLg_S';
const OUT_FILE = join(dirname(fileURLToPath(import.meta.url)), '../lib/sermons.js');
const PROGRESS_FILE = join(dirname(fileURLToPath(import.meta.url)), '../scripts/index-progress.json');
const REINDEX = process.argv.includes('--reindex');

function loadProgress() {
  if (existsSync(PROGRESS_FILE)) return JSON.parse(readFileSync(PROGRESS_FILE, 'utf8'));
  return {};
}

function saveProgress(p) {
  writeFileSync(PROGRESS_FILE, JSON.stringify(p, null, 2));
}

async function getAccessToken() {
  const auth = new GoogleAuth({
    credentials: {
      client_email: process.env.GOOGLE_CLIENT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    },
    scopes: ['https://www.googleapis.com/auth/drive.readonly'],
  });
  const client = await auth.getClient();
  const token = await client.getAccessToken();
  return token.token;
}

async function getAllFiles(token) {
  let files = [], pageToken = null;
  do {
    const params = new URLSearchParams({
      q: `'${FOLDER_ID}' in parents and mimeType = 'text/plain'`,
      fields: 'nextPageToken,files(id,name)',
      pageSize: '100',
    });
    if (pageToken) params.set('pageToken', pageToken);
    const res = await fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    const data = await res.json();
    files = files.concat(data.files || []);
    pageToken = data.nextPageToken || null;
  } while (pageToken);
  return files;
}

async function readFile(fileId, token) {
  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  return res.text();
}

async function extractMetadata(title, text, anthropic) {
  const prompt = `You are indexing a BJosh (Bishop Joshua Heward-Mills) sermon transcript for a search engine. This transcript was auto-generated by speech-to-text software, so it has NO punctuation, inconsistent capitalization, and scripture references are spoken aloud rather than written (e.g. "john chapter three verse sixteen" or "romans eight and twenty eight" or he may just quote the verse without naming it).

Sermon title: "${title}"

Transcript:
${text.slice(0, 40000)}

Your job:
1. Find ALL Bible scripture references — listen for spoken patterns like "john three sixteen", "first corinthians fourteen", "the book of romans chapter eight", "genesis chapter one", etc. Convert them to standard format: "John 3:16", "1 Corinthians 14", "Romans 8", etc.
2. Extract specific topic keywords central to the teaching.
3. Identify the single most central scripture.
4. Write a 3-sentence summary of what BJosh specifically teaches.

The transcript text shown above is exactly what was provided to you — there is no separate document to "access" and no authentication step on your end, so never describe missing content as an "authentication error" or "could not be accessed". If the transcript is present but is only worship-song lyrics, crowd noise, or garbled/repetitive speech-to-text output with no discernible teaching, say exactly that in plain terms (e.g. "This transcript consists only of worship song lyrics with no sermon content" or "This transcript is garbled speech-to-text with no discernible teaching content") and return empty arrays/strings for topics, scriptures, and keyScripture.

Return ONLY this JSON, nothing else:
{
  "topics": ["8-12 specific topic keywords — not generic words like God or church"],
  "scriptures": ["all Bible references found, in standard format e.g. John 3:16"],
  "keyScripture": "the single most central scripture or empty string if truly none",
  "summary": "exactly 3 sentences on what BJosh specifically teaches — be concrete"
}`;

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-5',
    max_tokens: 1200,
    messages: [{ role: 'user', content: prompt }],
  });

  const raw = response.content[0].text.replace(/```json|```/g, '').trim();
  return JSON.parse(raw);
}

async function main() {
  if (!process.env.GOOGLE_CLIENT_EMAIL || !process.env.GOOGLE_PRIVATE_KEY || !process.env.ANTHROPIC_API_KEY) {
    console.error('Set GOOGLE_CLIENT_EMAIL, GOOGLE_PRIVATE_KEY, ANTHROPIC_API_KEY');
    process.exit(1);
  }

  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const progress = loadProgress();

  if (REINDEX) {
    console.log('--reindex mode: will re-process entries with empty scriptures\n');
  }

  console.log('Authenticating with Google...');
  const token = await getAccessToken();

  console.log('Fetching sermon list...');
  const files = await getAllFiles(token);
  console.log(`Found ${files.length} transcripts\n`);

  const results = { ...progress };
  let newCount = 0;

  for (let i = 0; i < files.length; i++) {
    const f = files[i];
    const title = f.name.replace('.txt', '');
    const existing = results[f.id];

    const needsReindex = REINDEX && existing && existing.scriptures?.length === 0;
    if (existing && !needsReindex) {
      console.log(`[${i+1}/${files.length}] Cached: ${title}`);
      continue;
    }

    console.log(`[${i+1}/${files.length}] ${needsReindex ? 'Re-indexing' : 'Indexing'}: ${title}`);

    try {
      const text = await readFile(f.id, token);
      let meta;
      for (let attempt = 1; attempt <= 3; attempt++) {
        try {
          meta = await extractMetadata(title, text, anthropic);
          break;
        } catch (retryErr) {
          if (attempt === 3) throw retryErr;
          console.log(`  → Retry ${attempt}/3 after error: ${retryErr.message}`);
          await new Promise(r => setTimeout(r, 5000 * attempt));
        }
      }
      results[f.id] = { driveId: f.id, title, ...meta };
      newCount++;
      saveProgress(results);
      console.log(`  → ${meta.scriptures.length} scriptures · ${meta.topics.length} topics`);
      await new Promise(r => setTimeout(r, 1500));
    } catch (e) {
      console.log(`  → Error: ${e.message}`);
    }
  }

  const sermons = Object.values(results).map((s, i) => ({ id: i + 1, ...s }));
  const js = 'export const SERMONS = ' + JSON.stringify(sermons, null, 2) + ';\n';
  writeFileSync(OUT_FILE, js);

  console.log(`\nDone. ${newCount} processed · ${sermons.length} total · written to lib/sermons.js`);
}

main().catch(console.error);